---
title: "Azimuth annotation of C133_Neeland data"
subtitle: "Batches 0-6 (No ambient removal)"
author: "Jovana Maksimovic"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
site: workflowr::wflow_site
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
    number_sections: true
---

```{r, echo = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Load libraries

```{r, message=FALSE, warning=FALSE}
suppressPackageStartupMessages({
  library(BiocStyle)
  library(tidyverse)
  library(here)
  library(glue)
  library(patchwork)
  library(scran)
  library(scater)
  library(scuttle)
  library(scMerge)
  library(ggupset)
  library(Seurat)
  library(SeuratData)
  library(Azimuth)
})
```


# Load data

```{r}
files <- list.files(here("data",
                         paste0("C133_Neeland_batch", 0:6),
                         "data", 
                         "SCEs"), 
                    pattern = "ambient_removed",
                    full.names = TRUE)
  
sceLst <- sapply(files, function(fn){
    readRDS(file = fn)
})

sceLst
```
## Convert to *Seurat* objects

```{r}
seuLst <- sapply(sceLst, function(sce){
  # Azimuth relies on gene symbols for annotation to add these as row names
  rownames(sce) <- rowData(sce)$Symbol
  
  # sum any rows that have the same gene symbol
  CAGEfightR::utilsAggregateRows(counts(sce), 
                                 factor(rownames(sce)), 
                                 sparse = TRUE) -> count_matrix 
  
  seu <- Seurat::CreateSeuratObject(counts = count_matrix,
                                    meta.data = data.frame(colData(sce)))
  seu
})

seuLst
```

# Annotate 

```{r, warning=FALSE, message=FALSE}
options(timeout = max(1000000, getOption("timeout")))
batches <- str_extract(names(seuLst), "batch[0-6]")

seuLst <- sapply(1:length(seuLst), function(i){
  out <-  here("data",
               paste0("C133_Neeland_", batches[i]),
               "data", 
               "SCEs", 
               glue("C133_Neeland_{batches[i]}.azimuth_annotated.SEU.rds"))
  
  if(!file.exists(out)){
    tmp <- RunAzimuth(seuLst[[i]], reference = "lungref")
    seu <- seuLst[[i]]
    seu@meta.data <- tmp@meta.data
    seu@reductions$ref.umap <- tmp@reductions$ref.umap
    
    if(!is_empty(altExpNames(sceLst[[i]]))){
      seu[["ADTs"]] <- CreateAssayObject(counts = counts(altExp(sceLst[[i]], 
                                                                "ADT")))
      
    }
    
  } else {
    seu <- readRDS(out)
    
  }
  seu
  
})

seuLst
```


```{r, fig.asp=1.5}
p <- lapply(seuLst, function(seu){
  DimPlot(seu, reduction = "ref.umap", group.by = "predicted.ann_level_3",
          label = TRUE, label.size = 2.75) + 
    NoLegend() +
    paletteer::scale_color_paletteer_d("miscpalettes::pastel") -> p1
  DimPlot(seu, reduction = "ref.umap", group.by = "predicted.ann_level_4",
          label = TRUE, label.size = 2.5) + NoLegend() -> p2
  p1 / p2
})

p
```


# Save data

```{r}
names(seuLst) <- names(sceLst)
batches <- str_extract(names(seuLst), "batch[0-6]")

sapply(1:length(seuLst), function(i){
  out <-  here("data",
               paste0("C133_Neeland_", batches[i]),
               "data", 
               "SCEs", 
               glue("C133_Neeland_{batches[i]}.azimuth_annotated.SEU.rds"))
  if(!file.exists(out)) saveRDS(seuLst[[i]], out)
  fs::file_chmod(out, "664")
  if(any(str_detect(fs::group_ids()$group_name, 
                    "oshlack_lab"))) fs::file_chown(out, 
                                                    group_id = "oshlack_lab")
})
```


# Session info {.appendix}


