---
title: "Azimuth annotation of C133_Neeland data"
subtitle: "Batches 0-6 (Ambient RNA removed)"
author: "Jovana Maksimovic"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
site: workflowr::wflow_site
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
    number_sections: true
---

```{r, echo = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Load libraries

```{r, message=FALSE, warning=FALSE}
suppressPackageStartupMessages({
  library(BiocStyle)
  library(tidyverse)
  library(here)
  library(glue)
  library(patchwork)
  library(scran)
  library(scater)
  library(scuttle)
  library(scMerge)
  library(ggupset)
  library(Seurat)
  library(SeuratData)
  library(Azimuth)
})
```


# Load data

```{r}
files <- list.files(here("data",
                         paste0("C133_Neeland_batch", 0:6),
                         "data", 
                         "SCEs"), 
                    pattern = "ambient_removed",
                    full.names = TRUE)
  
sceLst <- sapply(files, function(fn){
    readRDS(file = fn)
})

sceLst
```
## Convert to *Seurat* objects

```{r}
seuLst <- sapply(sceLst, function(sce){
  # Azimuth relies on gene symbols for annotation to add these as row names
  rownames(sce) <- rowData(sce)$Symbol
  
  # use rounded, ambient removed counts from decontX 
  # sum any rows that have the same gene symbol
  CAGEfightR::utilsAggregateRows(round(assay(sce, "decontXcounts")), 
                                 factor(rownames(sce)), 
                                 sparse = TRUE) -> count_matrix 
  
  seu <- Seurat::CreateSeuratObject(counts = count_matrix,
                                    meta.data = data.frame(colData(sce)))
  seu
})

seuLst
```

# Azimuth annotate 

Annotate cells in each batch using the Human Lung Cell Atlas v2.0 reference.

```{r, warning=FALSE, message=FALSE}
options(timeout = max(1000000, getOption("timeout")))
batches <- str_extract(names(seuLst), "batch[0-6]")

seuLst <- sapply(1:length(seuLst), function(i){
  out <-  here("data",
               paste0("C133_Neeland_", batches[i]),
               "data", 
               "SCEs", 
               glue("C133_Neeland_{batches[i]}.azimuth_annotated_decontx.SEU.rds"))
  
  if(!file.exists(out)){
    tmp <- RunAzimuth(seuLst[[i]], reference = "lungref")
    seu <- seuLst[[i]]
    seu@meta.data <- tmp@meta.data
    seu@reductions$ref.umap <- tmp@reductions$ref.umap
    
    if(!is_empty(altExpNames(sceLst[[i]]))){
      seu[["ADTs"]] <- CreateAssayObject(counts = counts(altExp(sceLst[[i]], 
                                                                "ADT")))
      
    }
    
    saveRDS(seu, out)
    fs::file_chmod(out, "664")
    if(any(str_detect(fs::group_ids()$group_name, 
                      "oshlack_lab"))) fs::file_chown(out, 
                                                      group_id = "oshlack_lab")
    
  } else {
    seu <- readRDS(out)
    
  }
  seu
  
})

seuLst
```


```{r, fig.asp=1.5}
p <- lapply(seuLst, function(seu){
  DimPlot(seu, reduction = "ref.umap", group.by = "predicted.ann_level_3",
          label = TRUE, label.size = 2.75) + 
    NoLegend() +
    paletteer::scale_color_paletteer_d("miscpalettes::pastel") -> p1
  DimPlot(seu, reduction = "ref.umap", group.by = "predicted.ann_level_4",
          label = TRUE, label.size = 2.5) + NoLegend() -> p2
  p1 / p2
})

p
```


# Merge batches and save object

Create a single `Seurat` object and clean-up the metadata.

```{r}
out <- here("data/C133_Neeland_full_clean_decontx.SEU.rds")

if(!file.exists(out)){
  seu <- merge(seuLst[[1]], 
               y = c(seuLst[2:7]))
  rm(seuLst)
  gc()
  
  meta_regex <- "altexps|vireo|hashedDrops|refAssay|batch|Sample|sum|^detected|^dmmHTO|^Capture.|^total|mito_|percent.mt|orig|_call|_score|^scDblFinder|subsets"
  keep <- !str_detect(colnames(seu@meta.data), meta_regex)
  seu@meta.data <- seu@meta.data[, keep]
  
  # extract RNA counts
  rna <- seu[["RNA"]]@counts
  # remove genes that are not expressed in any cells
  rna <- rna[rowSums(rna) != 0, ]
  # remove genes that are not expressed in >=50 cells across the full dataset
  rna <- rna[nexprs(rna, byrow = TRUE) >= 50,]
  
  seu[["RNA"]] <- CreateAssayObject(counts = rna)
  
  saveRDS(seu, out)
  fs::file_chmod(out, "664")
  if(any(str_detect(fs::group_ids()$group_name, 
                    "oshlack_lab"))) fs::file_chown(out, 
                                                    group_id = "oshlack_lab")
  
} else {
  rm(seuLst)
  gc()
  seu <- readRDS(out)
  
}

seu
```


# Save cell type group objects

Subset cell type groups.

```{r}
cellsLst <- list(macrophages = seu[, seu$predicted.ann_level_3 == "Macrophages"],
                 t_cells = seu[, seu$predicted.ann_level_3 %in% c("T cell lineage", 
                                                                  "Innate lymphoid cell NK")],
                 other_cells = seu[, !seu$predicted.ann_level_3 %in% c("Macrophages", 
                                                                       "T cell lineage", 
                                                                       "Innate lymphoid cell NK")])

cellsLst
```

Save objects.

```{r}
sapply(1:length(cellsLst), function(i){
  out <- here("data",
              glue("C133_Neeland_full_clean_decontx_{names(cellsLst[i])}.SEU.rds"))
  
  if(!file.exists(out)) saveRDS(cellsLst[[i]], out)
  fs::file_chmod(out, "664")
  if(any(str_detect(fs::group_ids()$group_name, 
                    "oshlack_lab"))) fs::file_chown(out, 
                                                    group_id = "oshlack_lab")
})
```


# Session info {.appendix}


