---
title: "Figure 2"
author: "Jovana Maksimovic"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
site: workflowr::wflow_site
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load libraries.

```{r}
suppressPackageStartupMessages({
 library(SingleCellExperiment)
 library(edgeR)
 library(tidyverse)
 library(ggplot2)
 library(Seurat)
 library(glmGamPoi)
 library(dittoSeq)
 library(here)
 library(clustree)
 library(patchwork)
 library(AnnotationDbi)
 library(org.Hs.eg.db)
 library(glue)
 library(speckle)
 library(tidyHeatmap)
 library(paletteer)
 library(dsb)
 library(ggh4x)
  library(readxl)
})

source(here("code/utility.R"))
```

# Load data

```{r}
files <- list.files(here("data/C133_Neeland_merged"),
                    pattern = "C133_Neeland_full_clean.*(macrophages|t_cells|other_cells)_annotated_full.SEU.rds",
                    full.names = TRUE)

seuLst <- lapply(files, function(f) readRDS(f))
seuLst
```

# Macrophage cells figure panels

```{r}
lab_map <- c(
  "macro-alveolar"          = "AM",
  "macro-IGF1"              = "AM.IGF1",
  "macro-CCL"               = "AM.CCL",
  "macro-lipid"             = "AM.Lipid",
  "macro-MT"                = "AM.MT",
  "macro-IFN"               = "AM.IFN",
  "macro-APOC2+"            = "AM.APOC2",
  "macro-CCL18"             = "AM.CCL18",
  "macro-IFI27"             = "AM.IFI27",
  "macro-monocyte-derived"  = "Mac.Mono.Deriv",
  "macro-interstitial"      = "Mac.Interstitial",
  "macro-lipid-APOC2+"      = "AM.Lipid.APOC2",
  "macro-T"                 = "Mac.T",
  "macro-IFI27+CCL18+"      = "AM.IFI27.CCL18",
  "macro-IFI27+APOC2+"      = "AM.IFI27.APOC2",
  "macro-proliferating"     = "Mac.Prolif"    # ← collapse proliferating
)
```

Map long cell type labels to short labels.

```{r}
seuLst[[3]]$ann_level_3 <- ifelse(str_detect(seuLst[[3]]$ann_level_3, "proliferating"),
                                  "macro-proliferating",
                                  seuLst[[3]]$ann_level_3)
# map long labels to short labels
seuLst[[3]]$short_labels <- lab_map[seuLst[[3]]$ann_level_3]
# match ordering of the levels betwen long and short labels
lut <- unique(seuLst[[3]]@meta.data[, c("ann_level_3", "short_labels")])
lut <- lut[match(levels(factor(seuLst[[3]]$ann_level_3)), lut$ann_level_3), , drop = FALSE]
# update level ordering for short labels
seuLst[[3]]$short_labels <- factor(seuLst[[3]]$short_labels, 
                                   levels = unique(lut$short_labels))
```

```{r}
options(ggrepel.max.overlaps = Inf)
cluster_pal <- "ggsci::category20_d3"

draw_umap_with_labels(seuLst[[3]], 
                      ann_level = "short_labels", 
                      cluster_pal) -> f2a
f2a
```

```{r, fig.width=13, fig.asp=0.4}
#markers <- readRDS(here("data/cluster_annotations/seurat_markers_macrophages.rds"))
# 
# draw_marker_gene_dotplot(seuLst[[3]],
#                          markers,
#                          "ann_level_3",
#                          cluster_pal)

labels <- read_excel(here("data",
                          "cluster_annotations",
                          "marker_genes_macrophages_figure_2.xlsx"))
                          #"macrophages_26.06.24.xlsx"))

unnest(enframe(setNames(str_split(labels$`non-overlapping marker genes`, ", "),
                        labels$`cell label`),
               value = "gene",
               name = "cluster"),
       cols = gene) %>%
  arrange(cluster) %>%
  distinct() -> markers

markers <- markers[markers$gene %in% rownames(seuLst[[3]]),]

draw_marker_gene_dotplot(seuLst[[3]], 
                         markers, 
                         ann_level = "ann_level_3", 
                         cluster_pal,
                         lab_map = lab_map,
                         direction = 1,
                         num = 5,
                         strip.text.blank = TRUE,
                         strip.alpha = 1,
                         dot.scale = 3) -> f2b

f2b
```

```{r}
samp_map <-
c(
  "CF.IVA" = "CF (iva)",
  "CF.LUMA_IVA" = "CF (luma/iva)",
  "CF.NO_MOD" = "CF (no mod)",
  "NON_CF.CTRL" = "Non-CF control"
)

seuLst[[3]]$Group <- samp_map[seuLst[[3]]$Group]

# Map colours to groups
strip_colours <- c(   
  "CF (iva)" = "#66C2A5",
  "CF (luma/iva)" = "#FC8D62",
  "CF (no mod)" = "#8DA0CB",
  "Non-CF control" = "#E78AC3"
)
```

```{r}
draw_cell_type_proportions_barplot(seuLst[[3]],
                                   ann_level = "short_labels",
                                   cluster_pal,
                                   strip_colours = strip_colours) -> f2c

f2c
```


# T/NK cells figure panels

```{r}
lab_map <- c(
  "CD4 T cells"         = "CD4 T",
  "CD4 T-IFN"           = "CD4 T-IFN",
  "CD4 T-naïve"         = "CD4 T-naïve",   # use "CD4 naive" if you want ASCII
  "CD4 T-NFKB"          = "CD4 T-NFκB",    # use "CD4 NFKB" for ASCII
  "CD4 T-reg"           = "CD4 T-reg",
  "CD4 T-rm"            = "CD4 T-rm",
  "CD8 T-GZMK"          = "CD8 T-GZMK",
  "CD8 T-inflammasome"  = "CD8 T-inflam",
  "CD8 T-rm"            = "CD8 T-rm",
  "gamma delta T cells" = "γδ T",        # or "gd T"
  "innate lymphocytes"  = "ILC",
  "NK cells"            = "NK",
  "NK-T cells"          = "NKT",
  "proliferating T/NK"  = "Prolif T/NK"
)
```

Map long cell type labels to short labels.

```{r}
# map long labels to short labels
seuLst[[2]]$short_labels <- lab_map[seuLst[[2]]$ann_level_3]
# match ordering of the levels betwen long and short labels
lut <- unique(seuLst[[2]]@meta.data[, c("ann_level_3", "short_labels")])
lut <- lut[match(levels(factor(seuLst[[2]]$ann_level_3)), lut$ann_level_3), , drop = FALSE]
# update level ordering for short labels
seuLst[[2]]$short_labels <- factor(seuLst[[2]]$short_labels, 
                                   levels = unique(lut$short_labels))
```

```{r}
cluster_pal <- "ggsci::category20b_d3"

draw_umap_with_labels(seuLst[[2]], 
                      "short_labels", 
                      cluster_pal,
                      direction = -1) -> f2d

f2d
```

```{r, fig.width=12, fig.asp=0.4}
# markers <- readRDS(here("data/cluster_annotations/seurat_markers_TNK_cells.rds"))
# 
# draw_marker_gene_dotplot(seuLst[[2]],
#                          markers,
#                          "ann_level_3",
#                          cluster_pal,
#                          direction = -1) 
labels <- read_excel(here("data",
                          "cluster_annotations",
                          #"T-NK_ambientRNAremoval_21.03.24.xlsx"),
                          "marker_genes_TNK_figure_2.xlsx"))
                     #skip = 1)
  
unnest(enframe(setNames(str_split(labels$`non-overlapping marker genes`, ", "),
                        labels$`cell label`),
               value = "gene",
               name = "cluster"),
       cols = gene) %>%
  arrange(cluster) %>%
  distinct() %>%
  dplyr::filter(gene != "MALAT1") -> markers

markers <- markers[markers$gene %in% rownames(seuLst[[2]]),]

draw_marker_gene_dotplot(seuLst[[2]], 
                         markers, 
                         ann_level = "ann_level_3", 
                         cluster_pal,
                         lab_map = lab_map,
                         direction = 1,
                         num = 5,
                         strip.text.blank = TRUE,
                         strip.alpha = 1,
                         dot.scale = 5) -> f2e

f2e
```

```{r}
seuLst[[2]]$Group <- samp_map[seuLst[[2]]$Group]

draw_cell_type_proportions_barplot(seuLst[[2]],
                                   ann_level = "short_labels",
                                   cluster_pal,
                                   strip_colours = strip_colours,
                                   direction = -1) -> f2f

f2f
```

# Rare cells figure panels

```{r}
lab_map <- c(
  "B cells"                   = "B",
  "cDC1"                      = "cDC1",
  "cDC2"                      = "cDC2",
  "ciliated epithelial cells" = "Ciliated epi",
  "dividing innate cells"     = "Div innate",
  "HSP+ B cells"              = "HSP+ B",
  "mast cells"                = "Mast",
  "migratory DC"              = "Mig DC",
  "monocytes"                 = "Mono",
  "neutrophil-like"           = "Neut-like",
  "plasma B cells"            = "Plasma B",
  "plasmacytoid DC"           = "pDC",
  "secretory epithelial cells"= "Secretory epi"
)
```

Map long cell type labels to short labels.

```{r}
# map long labels to short labels
seuLst[[1]]$short_labels <- lab_map[seuLst[[1]]$ann_level_3]
# match ordering of the levels betwen long and short labels
lut <- unique(seuLst[[1]]@meta.data[, c("ann_level_3", "short_labels")])
lut <- lut[match(levels(factor(seuLst[[1]]$ann_level_3)), lut$ann_level_3), , drop = FALSE]
# update level ordering for short labels
seuLst[[1]]$short_labels <- factor(seuLst[[1]]$short_labels, 
                                   levels = unique(lut$short_labels))
```

```{r}
cluster_pal <- "ggsci::category20c_d3"

draw_umap_with_labels(seuLst[[1]], 
                      "short_labels", 
                      cluster_pal) -> f2g

f2g
```

```{r, fig.width=13, fig.asp=0.4}
# markers <- readRDS(here("data/cluster_annotations/seurat_markers_other_cells.rds"))
# 
# draw_marker_gene_dotplot(seuLst[[1]],
#                          markers,
#                          "ann_level_3",
#                          cluster_pal) 

labels <- read_excel(here("data",
                          "cluster_annotations",
                          #"others_ambientRNAremoval_21.03.24.xlsx"),
                          "marker_genes_other_figure_2.xlsx"))
                     #skip = 1)
  
unnest(enframe(setNames(str_split(labels$`non-overlapping marker genes`, ", "),
                        labels$`cell label`),
               value = "gene",
               name = "cluster"),
       cols = gene) %>%
  arrange(cluster) %>%
  distinct() -> markers

markers <- markers[markers$gene %in% rownames(seuLst[[1]]),]

draw_marker_gene_dotplot(seuLst[[1]], 
                         markers, 
                         ann_level = "ann_level_3", 
                         cluster_pal,
                         lab_map = lab_map,
                         direction = 1,
                         num = 5,
                         strip.text.blank = TRUE,
                         strip.alpha = 1,
                         dot.scale = 4) -> f2h

f2h
```

```{r}
seuLst[[1]]$Group <- samp_map[seuLst[[1]]$Group]

draw_cell_type_proportions_barplot(seuLst[[1]],
                                   ann_level = "short_labels",
                                   cluster_pal,
                                   strip_colours = strip_colours) -> f2i

f2i
```

# Figure 2

```{r, fig.width=16, fig.asp=1.3}
layout = "
AAABBBBB
AAACCCCC
DDDEEEEE
DDDFFFFF
GGGHHHHH
GGGIIIII
"
(wrap_elements(f2a + theme(plot.margin = unit(rep(0,4), "cm"))) +
    wrap_elements(f2b + theme(plot.margin = unit(rep(0,4), "cm"),
                              legend.justification = "left")) +
    wrap_elements(f2c + theme(plot.margin = unit(rep(0,4), "cm"),
                              legend.spacing = unit(0.1, "lines"))) +
    wrap_elements(f2d + theme(plot.margin = unit(rep(0,4), "cm"))) +
    wrap_elements(f2e + theme(plot.margin = unit(rep(0,4), "cm"),
                              legend.justification = "left")) +
    wrap_elements(f2f + theme(plot.margin = unit(rep(0,4), "cm"),
                              legend.spacing = unit(0.1, "lines"))) +
    wrap_elements(f2g + theme(plot.margin = unit(rep(0,4), "cm"))) +
    wrap_elements(f2h + theme(plot.margin = unit(rep(0,4), "cm"),
                              legend.justification = "left")) +
    wrap_elements(f2i + theme(plot.margin = unit(rep(0,4), "cm"),
                              legend.spacing = unit(0.1, "lines")))) +
  plot_layout(design = layout) +
  plot_annotation(tag_levels = "A") &
  theme(plot.tag = element_text(size = 24,
                                face = "bold",
                                family = "arial")) -> p

p

ggsave(here("output/pdf_figures/Figure_2.pdf"), 
       plot = p, width = 16, height = 22, units = "in", device = cairo_pdf)
```



# Session info










