---
title: "Figure 3"
author: "Jovana Maksimovic"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
site: workflowr::wflow_site
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load libraries.

```{r}
suppressPackageStartupMessages({
 library(SingleCellExperiment)
 library(edgeR)
 library(tidyverse)
 library(ggplot2)
 library(Seurat)
 library(glmGamPoi)
 library(dittoSeq)
 library(here)
 library(clustree)
 library(patchwork)
 library(AnnotationDbi)
 library(org.Hs.eg.db)
 library(glue)
 library(speckle)
 library(tidyHeatmap)
 library(paletteer)
 library(dsb)
 library(ggh4x)
  library(readxl)
  library(purrr)
})

source(here("code/utility.R"))
```

# Load data

```{r}
files <- list.files(here("data/C133_Neeland_merged"),
                    pattern = "C133_Neeland_full_clean.*(macrophages|t_cells|other_cells)_annotated_diet.SEU.rds",
                    full.names = TRUE)

seuLst <- lapply(files[2:4], function(f) readRDS(f))

seu <- merge(seuLst[[1]], 
             y = c(seuLst[[2]], 
                   seuLst[[3]]))
seu
```


```{r, echo=FALSE}
# cleanup obsolete objects
rm(seuLst)
gc()
```


Create sample meta data table.

```{r}
props <- getTransformedProps(clusters = seu$ann_level_3,
                             sample = seu$sample.id, transform="asin")

seu@meta.data %>%
  dplyr::select(sample.id,
                Participant,
                Disease,
                Treatment,
                Severity,
                Group,
                Group_severity,
                Batch, 
                Age, 
                Sex) %>%
     left_join(props$Counts %>% 
                 data.frame %>%
                 group_by(sample) %>%
                 summarise(ncells = sum(Freq)),
               by = c("sample.id" = "sample")) %>%
    distinct() -> info

head(info) %>% knitr::kable()
```

# Prepare figure panels

Set up short/better names for cell types and conditions in figure.

```{r}
lab_map <- c(
  "macro-alveolar"          = "AM",
  "macro-IGF1"              = "AM.IGF1",
  "macro-CCL"               = "AM.CCL",
  "macro-lipid"             = "AM.Lipid",
  "macro-MT"                = "AM.MT",
  "macro-IFN"               = "AM.IFN",
  "macro-APOC2+"            = "AM.APOC2",
  "macro-CCL18"             = "AM.CCL18",
  "macro-IFI27"             = "AM.IFI27",
  "macro-monocyte-derived"  = "Mac.Mono.Deriv",
  "macro-interstitial"      = "Mac.Interstitial",
  "macro-lipid-APOC2+"      = "AM.Lipid.APOC2",
  "macro-T"                 = "Mac.T",
  "macro-IFI27+CCL18+"      = "AM.IFI27.CCL18",
  "macro-IFI27+APOC2+"      = "AM.IFI27.APOC2",
  "macro-proliferating"     = "Mac.Prolif",
  "macrophages"             = "All Macs (exc. Prolif)",
  "CD4 T-reg" = "CD4 T-reg",
  "monocytes" = "monocytes",
  "NK-T cells" = "NK-T cells"
)

samp_map <-
c(
  "CF.IVA" = "CF (iva)",
  "CF.LUMA_IVA" = "CF (luma/iva)",
  "CF.NO_MOD" = "CF (no mod)",
  "NON_CF.CTRL" = "Non-CF control",
  "healthy" = "Control",
  "mild" = "Mild",
  "severe" = "Severe"
)
```

```{r, fig.asp=0.5}
# 3A: monocytes, NK-T cells, CD4 Tregs, macro-IGF1

props <- getTransformedProps(clusters = seu$ann_level_3[!str_detect(seu$ann_level_3, "macro")],
                             sample = seu$sample.id[!str_detect(seu$ann_level_3, "macro")], transform="asin")

props$Proportions %>% data.frame %>%
  left_join(info,
            by = c("sample" = "sample.id")) %>%
  dplyr::filter(Group %in% c("CF.NO_MOD", "NON_CF.CTRL"),
                clusters %in% c("monocytes", 
                                "NK-T cells",
                                "CD4 T-reg")) -> dat

sig_names <- as_labeller(lab_map)

prop.non_macros.fit <- readRDS(here("data/intermediate_objects/prop.ann_level3.non-macrophages.fit.rds"))
prop.macros.fit <- readRDS(here("data/intermediate_objects/prop.ann_level3.macrophages.fit.rds"))

fits <- list(
  non_macros = prop.non_macros.fit,
  macros = prop.macros.fit
)

stats_all <- map_dfr(
  fits,
  ~ topTable(.x,
             coef = "CF.NO_MODvNON_CF.CTRL",
             n = Inf) %>%
      rownames_to_column("clusters"),
  .id = "fit"
)

stat_labels <- stats_all %>%
  filter(clusters %in% unique(dat$clusters)) %>%
  distinct(clusters, .keep_all = TRUE) %>%
  mutate(
    sig = case_when(
      adj.P.Val < 0.001 ~ "***",
      adj.P.Val < 0.01  ~ "**",
      adj.P.Val < 0.05  ~ "*",
      TRUE ~ ""
    ),
    label = sprintf("p = %.2g\nFDR = %.2g%s", 
                    P.Value, adj.P.Val, sig)
  )

y_pos <- dat %>%
  group_by(clusters) %>%
  summarise(y = max(Freq, na.rm = TRUE) * 0.9)

stat_labels <- left_join(stat_labels, y_pos, by = "clusters")

pal <- setNames(RColorBrewer::brewer.pal(7, "Set2"),
                unname(samp_map))
dat %>%
  mutate(Group = samp_map[Group]) %>%
  ggplot(aes(x = Group,
             y = Freq,
             colour = Group)) +
  geom_jitter(stat = "identity",
              width = 0.15,
              size = 1) +
  theme_classic() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 7),
        legend.position = "bottom",
        legend.direction = "horizontal",
        strip.text = element_text(size = 8)) +
  labs(x = "Group", y = "Proportion") +
  facet_wrap(~clusters, scales = "free_y", ncol = 4,
             labeller = sig_names) +
  stat_summary(
    geom = "point",
    fun.y = "mean",
    col = "black",
    shape = "_",
    size = 10) +
  scale_color_manual(values = pal) +
  geom_text(
  data = stat_labels,
  aes(x = 1.5, y = y, label = label),
  inherit.aes = FALSE,
  size = 3) -> p1

p1
```

```{r, fig.asp=0.4}
props <- getTransformedProps(clusters = seu$ann_level_3[str_detect(seu$ann_level_3, "macro")],
                             sample = seu$sample.id[str_detect(seu$ann_level_3, "macro")], transform="asin")

props$Proportions %>% data.frame %>%
  left_join(info,
            by = c("sample" = "sample.id")) %>%
  dplyr::filter(Group %in% c("CF.NO_MOD", "NON_CF.CTRL"),
                clusters %in% c("macro-IGF1")) -> dat

stat_labels <- stats_all %>%
  filter(clusters %in% unique(dat$clusters)) %>%
  distinct(clusters, .keep_all = TRUE) %>%
  mutate(
    sig = case_when(
      adj.P.Val < 0.001 ~ "***",
      adj.P.Val < 0.01  ~ "**",
      adj.P.Val < 0.05  ~ "*",
      TRUE ~ ""
    ),
    label = sprintf("p = %.2g\nFDR = %.2g%s", 
                    P.Value, adj.P.Val, sig)
  )

y_pos <- dat %>%
  group_by(clusters) %>%
  summarise(y = max(Freq, na.rm = TRUE) * 0.9)

stat_labels <- left_join(stat_labels, y_pos, by = "clusters")

dat %>%
  mutate(Group = samp_map[Group]) %>%
ggplot(aes(x = Group,
                y = Freq,
                colour = Group)) +
  geom_jitter(stat = "identity",
              width = 0.15,
              size = 1) +
  theme_classic() +
  theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 7),
          legend.position = "bottom",
          legend.direction = "horizontal",
          strip.text = element_text(size = 8)) +
  labs(x = "Group", y = "Proportion") +
  facet_wrap(~clusters, scales = "free_y", ncol = 4,
             labeller = sig_names) +
  stat_summary(
    geom = "point",
    fun.y = "mean",
    col = "black",
    shape = "_",
    size = 10) +
  scale_color_manual(values = pal)  +
  geom_text(
  data = stat_labels,
  aes(x = 1.5, y = y, label = label),
  inherit.aes = FALSE,
  size = 3) -> p2

layout <- "AAAB"
cf_props <- (p1 + 
                (p2 + theme(axis.title.y = element_blank()))) + 
  plot_layout(design = layout, guides = "collect") &
  theme(axis.text.y = element_text(size = 6,
                                   angle = 90,
                                   hjust = 0.5),
        legend.text = element_text(size = 8),
        legend.key.spacing = unit(0, "lines"),
        legend.margin = margin(-0.5,0,0,0, unit="lines"),
        legend.direction = "horizontal",
        legend.position = "bottom") 

cf_props
```



```{r}
seu@meta.data %>% 
    data.frame %>% 
    dplyr::select(ann_level_2) %>%
    dplyr::filter(str_detect(ann_level_2, "macro")) %>%
    group_by(ann_level_2) %>% 
    count() %>%
    janitor::adorn_totals(name = "macrophages") %>%
    arrange(-n) %>%
    dplyr::rename(cell = ann_level_2) -> cell_freq

cell_freq
```

```{r}
files <- list.files(here("data/intermediate_objects"),
            pattern = "macro.*all_samples", 
            full.names = TRUE) 
 
cutoff <- 0.05 
cont_name <- "CF.NO_MODvNON_CF.CTRL"
lfc_cutoff <- log2(1.1)
suffix <- ".all_samples.fit.rds"
  
get_deg_data(files, cont_name, cell_freq, treat_lfc = lfc_cutoff,
             suffix = suffix) -> dat
```

```{r}
dat %>%
  dplyr::select(gene, cell, logFC) %>%
  distinct() %>%
  pivot_wider(
    names_from = cell,        # Column whose values become new column names
    values_from = logFC,
    values_fill = list(logFC = NA)) %>%
   arrange(across(all_of(cell_freq$cell[cell_freq$cell %in% dat$cell]))) %>%
  column_to_rownames(var = "gene") -> dat_lfc
```

```{r, fig.asp=1.75}
col_fun <- circlize::colorRamp2(seq(0, 100000, length.out = 9), 
                                (RColorBrewer::brewer.pal(9, "PiYG")))
col_split <- c(rep("aggregate", 1), rep("sub-type", ncol(dat_lfc) - 1))

pal_dt <- c(paletteer::paletteer_d("RColorBrewer::Set1")[2:1], "grey") 
col_lfc_fun <- circlize::colorRamp2(seq(-2, 2, length.out = 3), 
                                    c(pal_dt[1], "white", pal_dt[2]))

ComplexHeatmap::HeatmapAnnotation(df = cell_freq %>%
                                    dplyr::filter(cell %in% colnames(dat_lfc)) %>%
                                    column_to_rownames(var = "cell") %>%
                                    dplyr::rename(`No. cells` = n),
                                  which = "column",
                                  show_annotation_name = FALSE,
                                  col = list(`No. cells` = col_fun),
                                  annotation_legend_param = list(
                                    `No. cells` = list(direction = "vertical"))) -> col_ann

ComplexHeatmap::HeatmapAnnotation(df = data.frame(`Sig. ≥2 cell types` = (rowSums(!is.na(dat_lfc)) > 1),
                                                  check.names = FALSE),
                                  which = "row",
                                  col = list(`Sig. ≥2 cell types` = c("FALSE" = "#fdcce5","TRUE" = "#8bd3c7")),
                                  annotation_legend_param = list(
                                    `Sig. ≥2 cell types` = list(direction = "vertical",
                                                    ncol = 1)),
                                  show_annotation_name = FALSE) -> row_ann

colnames(dat_lfc) <- lab_map[colnames(dat_lfc)]
ComplexHeatmap::Heatmap(dat_lfc, 
                        name = "logFC",
                        column_split = col_split,
                        column_title = NULL,
                        cluster_rows = FALSE,
                        cluster_columns = FALSE,
                        rect_gp = grid::gpar(col = "white", lwd = 1),
                        row_names_gp = grid::gpar(fontsize = 7),
                        column_names_gp = grid::gpar(fontsize = 7),
                        col = col_lfc_fun,
                        top_annotation = col_ann,
                        right_annotation = row_ann,
                        heatmap_legend_param = list(direction = "vertical")) -> plot_lfc

ComplexHeatmap::draw(as(list(plot_lfc), "HeatmapList"), 
                     heatmap_legend_side = "right", 
                     annotation_legend_side = "right",
                     merge_legends = TRUE) -> plot_lfc
plot_lfc
```


```{r}
bind_rows(lapply(files, function(f){
  deg_results <- readRDS(f)
  lrt <- glmLRT(deg_results$fit, 
                contrast = deg_results$contr[,cont_name])
  tmp <- cbind(summary(decideTests(lrt, p.value = cutoff)) %>% data.frame,
                    cell = str_extract(basename(f), "^[^.]+"))
  tmp
})) -> dat_deg
```

```{r, fig.asp=1}
dat_deg %>% 
  left_join(cell_freq) -> dat_deg

pal_dt <- c(paletteer::paletteer_d("RColorBrewer::Set1")[2:1], "grey") 

dat_deg %>%
  dplyr::filter(Var1 != "NotSig") %>%
  mutate(cell = lab_map[as.character(cell)]) %>%
  ggplot(aes(x = fct_reorder(cell, n), y = Freq, fill = Var1)) +
  geom_col(position = "dodge") +
  scale_fill_manual(values = pal_dt) +
  theme_classic() +
  theme(axis.text.y = element_text(angle = -45,
                                   hjust = 1,
                                   vjust = 1,
                                   size = 7),
        legend.position = "top") +
  geom_text(aes(label = Freq), 
            position = position_dodge(width = 0.9),
            vjust = -0.5,
            angle = 270,
            size = 2.5) +
  labs(x = "Cell Type",
       y = "No. DEG (FDR < 0.05)",
       fill = "Direction") +
  coord_flip() -> deg_barplot

deg_barplot
```


```{r, fig.asp=1}
volc_plot <- draw_treat_volcano_plot(cell = "macrophages",
                                     suffix = suffix,
                                     cutoff = cutoff,
                                     lfc_cutoff = lfc_cutoff)
volc_plot
```


```{r}
Hs.c2.all <- convert_gmt_to_list(here("data/c2.all.v2024.1.Hs.entrez.gmt"))
Hs.h.all <- convert_gmt_to_list(here("data/h.all.v2024.1.Hs.entrez.gmt"))
Hs.c5.all <- convert_gmt_to_list(here("data/c5.all.v2024.1.Hs.entrez.gmt"))

fibrosis <- create_custom_gene_lists_from_file(here("data/fibrosis_gene_sets.csv"))
# add fibrosis sets from REACTOME and WIKIPATHWAYS
fibrosis <- c(lapply(fibrosis, function(l) l[!is.na(l)]),
              Hs.c2.all[str_detect(names(Hs.c2.all), "FIBROSIS")])

gene_sets_list <- list(HALLMARK = Hs.h.all,
                       GO = Hs.c5.all,
                       REACTOME = Hs.c2.all[str_detect(names(Hs.c2.all), "REACTOME")],
                       WP = Hs.c2.all[str_detect(names(Hs.c2.all), "^WP")],
                       FIBROSIS = fibrosis)

```


```{r, fig.asp=0.5}
# alveolar macrophages, macro-CCL, macro-lipid, Monocyte-derived macrophages
cell_types <- c("macro-alveolar", 
                "macro-monocyte-derived")

# TNFA signalling by NFKB, inflammatory responses, MTORC1 signalling, and cholesterol homeostasis

selected <- "ALLOGRAFT_REJECTION|ANDROGEN_RESPONSE"
results_list <- lapply(cell_types, function(cell_type){
  read_csv(file = here("output",
                       "dge_analysis",
                       cell_type,
                       "CAM.HALLMARK.CF.NO_MODvNON_CF.CTRL.csv")) %>%
    dplyr::filter(!str_detect(Set, selected)) %>%
    column_to_rownames(var = "Set") %>%
                       mutate(cell = cell_type)
})
names(results_list) <- rep("HALLMARK", length(results_list))

labels <- as_labeller(
     c("HALLMARK; macro-alveolar" = "AM",
       "HALLMARK; macro-monocyte-derived" = "Mac.Mono.Deriv"))
  
top_camera_sets_by_cell(results_list, num = 4, labeller = labels) + 
  theme(plot.title = element_blank(),
        axis.text.y = element_text(size = 7,
                                   angle = 0)) -> cam_plot_hallmark

cam_plot_hallmark
```

```{r, fig.asp=0.8}
# alveolar macrophages, macro-CCL, macro-lipid, Monocyte-derived macrophages
cell_types <- c("macro-alveolar", "macro-CCL", "macro-lipid",
                "macro-monocyte-derived")

# eukaryotic translation and elongation, SRP dependent cotranslational protein targeting to membrane, SARS-COV-1 and -2 host response and influenza infection
# L1CAM interactions, RHO GTPASES and IL-10 signalling

selected <- "EUKARYOTIC_TRANSLATION_ELONGATION|SRP_DEPENDENT_COTRANSLATIONAL|SARS_COV_1_MODULATES|SARS_COV_2_MODULATES|INFLUENZA_INFECTION|L1CAM_INTERACTIONS|INTERLEUKIN_10_SIGNALING|RHO_GTPASES_ACTIVATE_IQGAPS"
results_list <- lapply(cell_types, function(cell_type){
  read_csv(file = here("output",
                       "dge_analysis",
                       cell_type,
                       "CAM.REACTOME.CF.NO_MODvNON_CF.CTRL.csv")) %>%
    dplyr::filter(str_detect(Set, selected)) %>%
    column_to_rownames(var = "Set") %>%
                       mutate(cell = cell_type)
})
names(results_list) <- rep("REACTOME", length(results_list))

labels <- as_labeller(
     c("REACTOME; macro-alveolar" = "AM",
       "REACTOME; macro-CCL" = "AM-CCL",
       "REACTOME; macro-lipid" = "AM-lipid",
       "REACTOME; macro-monocyte-derived" = "Mac.Mono.Deriv"))

top_camera_sets_by_cell(results_list, num = 5, wrap_width = 50,
                        labeller = labels) + 
  theme(plot.title = element_blank(),
        axis.text.y = element_text(size = 6,
                                   angle = 30)) -> cam_plot_reactome

cam_plot_reactome 
```

```{r, fig.asp=0.5}
cell_types <- c("macrophages", "macro-alveolar")

fibrosis <- lapply(cell_types, function(cell_type){
  read_csv(file = here("output",
                       "dge_analysis",
                       cell_type,
                       "ORA.FIBROSIS.CF.NO_MODvNON_CF.CTRL.csv"))  %>%
    column_to_rownames(var = "Set") %>%
                       mutate(cell = cell_type)
})
names(fibrosis) <- rep("FIBROSIS", length(fibrosis))

wp <- lapply(cell_types, function(cell_type){
  read_csv(file = here("output",
                       "dge_analysis",
                       cell_type,
                       "ORA.WP.CF.NO_MODvNON_CF.CTRL.csv"))  %>%
    dplyr::filter(str_detect(Set, "PROFIBROTIC")) %>%
    column_to_rownames(var = "Set") %>%
                       mutate(cell = cell_type)
})
names(wp) <- rep("WP", length(wp))

results_list <- c(fibrosis, wp)

labels <- as_labeller(
     c("FIBROSIS; macro-alveolar" = "AM",
       "WP; macro-alveolar" = "AM",
       "FIBROSIS; macrophages" = "All Macs (exc. Prolif)",
       "WP; macrophages" = "All Macs (exc. Prolif)"))

top_ora_sets_by_cell(results_list, num = 2, wrap_width = 30,
                     labeller = labels) + 
  theme(plot.title = element_blank(),
        axis.text.y = element_text(size = 7,
                                   angle = 0)) -> ora_plot_fibrosis

ora_plot_fibrosis 
```


# Figure 3

```{r, fig.asp=1.8, fig.width=10}
layout <- "
AAAAAAA
BBBCCCC
BBBCCCC
BBBCCCC
DDDCCCC
DDDCCCC
EEECCCC
EEECCCC
EEECCCC
EEECCCC
GGGHHHH
GGGHHHH
"

wrap_elements(cf_props & theme(legend.position = "right",
                               legend.direction = "vertical",
                               plot.margin = margin(rep(0,4)))) +
  wrap_elements(deg_barplot + theme(plot.margin = margin(rep(0,4)),
                                  axis.text.y = element_text(size = 8))) +
  wrap_elements(grid::grid.grabExpr(ComplexHeatmap::draw(plot_lfc,
                                                         padding = unit(0, "mm")))) +
  wrap_elements(volc_plot + theme(plot.margin = margin(rep(0,4)))) +
  wrap_elements(cam_plot_reactome + theme(legend.position = "bottom",
                                          legend.direction = "horizontal",
                                          legend.box = "vertical",
                                          legend.margin = margin(-0.5,0,0,0, unit="lines"),
                                          legend.key.size = unit(0.5, unit="lines"),
                                          legend.text = element_text(size = 6),
                                          axis.title = element_text(size = 8),
                                          axis.text = element_text(size = 6),
                                          plot.margin = margin(rep(0,4)))) +
  wrap_elements(cam_plot_hallmark + theme(legend.position = "bottom",
                                          legend.direction = "horizontal",
                                          legend.box = "vertical",
                                          legend.margin = margin(-0.5,0,0,0, unit="lines"),
                                          legend.key.size = unit(0.5, unit="lines"),
                                          legend.text = element_text(size = 8),
                                          axis.text = element_text(size = 8),
                                          plot.margin = margin(rep(0,4)))) +
  wrap_elements(ora_plot_fibrosis + theme(plot.margin = margin(rep(0,4)),
                                          axis.text = element_text(size = 7))) +
  plot_layout(design = layout) +
  plot_annotation(tag_levels = "A")  &
  theme(plot.tag = element_text(size = 24,
                                face = "bold",
                                family = "arial"))

```


# Supplement

```{r}
library(ComplexHeatmap)
library(circlize)
library(msigdbr)
library(fgsea)

# ── Preparation function ───────────────────────────────────────────────────────
# Run once per cell type, returns all objects needed for plotting
deg_results <- lapply(files, function(f) readRDS(f))

prepare_tnfa <- function(idx, celltype_name, deg_results) {
  
  lrt <- glmLRT(deg_results[[idx]]$fit, contrast = deg_results[[idx]]$contr[,1])
  top <- topTags(lrt, n = Inf) %>% data.frame()
  
  entrez <- mapIds(
    org.Hs.eg.db,
    keys      = rownames(lrt),
    column    = "ENTREZID",
    keytype   = "SYMBOL",
    multiVals = "first"
  )
  
  mat     <- deg_results[[idx]]$adj$normalizedCounts %>% as.data.frame() %>% as.matrix()
  mat_log <- log2(mat + 0.5)
  mat_z   <- t(scale(t(mat_log)))
  
  metadata <- seu@meta.data
  metadata[match(colnames(mat_z), metadata$sample.id), ] %>%
    remove_rownames() %>%
    dplyr::select(sample.id, Group, Treatment, Severity, Age) %>%
    distinct() %>%
    dplyr::filter(Treatment %in% c("Healthy", "untreated")) -> metadata_subset
  
  sample_anno <- HeatmapAnnotation(
    Severity = samp_map[metadata_subset$Severity],
    Group    = samp_map[metadata_subset$Group],
    Age      = metadata_subset$Age
  )
  
  tnfa_genes <- top[unname(entrez[rownames(top)]) %in%
                      gene_sets_list$HALLMARK$HALLMARK_TNFA_SIGNALING_VIA_NFKB, ] %>%
    arrange(logFC)
  
  ranked_genes <- top %>%
    rownames_to_column(var = "gene") %>%
    arrange(desc(logFC)) %>%
    dplyr::select(gene, logFC) %>%
    deframe()
  
  hallmarks <- msigdbr(species = "Homo sapiens", category = "H") %>%
    split(x = .$gene_symbol, f = .$gs_name)
  
  set.seed(42)
  gsea_res <- fgsea(pathways = hallmarks, stats = ranked_genes,
                    minSize = 15, maxSize = 500, nperm = 1000)
  
  gsea_res_tidy <- gsea_res %>%
    arrange(pval) %>%
    #filter(padj < 0.05) %>%
    slice_min(pval, n = 20) %>%
    mutate(pathway = gsub("HALLMARK_", "", pathway))
  
  tnfa_row           <- gsea_res_tidy %>% filter(grepl("TNFA", pathway))
  tnfa_genes_leading <- if (nrow(tnfa_row) > 0) unlist(tnfa_row[1, 8]) else NULL
  
  tnfa_genes_min <- c("TNFAIP3", "NFKBIA", "TNF", "IL1B", "IL1A",
                      "CXCL2", "CXCL3", "NR4A1", "NR4A2")
  
  list(
    celltype_name      = celltype_name,
    lrt                = lrt,
    entrez             = entrez,
    mat_z              = mat_z,
    metadata_subset    = metadata_subset,
    sample_anno        = sample_anno,
    tnfa_genes         = tnfa_genes,
    tnfa_genes_min     = tnfa_genes_min,
    tnfa_genes_leading = tnfa_genes_leading,
    gsea_res_tidy      = gsea_res_tidy
  )
}

# ── Plot functions ─────────────────────────────────────────────────────────────

plot_barcode <- function(obj) {
  statistic <- sign(obj$lrt$table$logFC) * sqrt(obj$lrt$table$LR)
  id <- ids2indices(
    gene_sets_list$HALLMARK$HALLMARK_TNFA_SIGNALING_VIA_NFKB,
    unname(obj$entrez[rownames(obj$lrt)])
  )
  barcodeplot(
    statistics = statistic,
    index      = unlist(id),
    main       = glue("HALLMARK_TNFA_SIGNALING_VIA_NFKB — {obj$celltype_name}"),
    xlab       = glue("Signed LRT statistic (CF (no mod) - Non-CF (ctrl)) — {obj$celltype_name}")
  )
}

plot_gsea <- function(obj) {
  obj$gsea_res_tidy %>%
    mutate(direction = ifelse(NES > 0, "Up", "Down")) %>%
    ggplot(aes(x = -log10(padj), y = reorder(pathway, -log10(padj)),
               size = abs(NES), colour = direction)) +
    geom_point() +
    scale_colour_manual(values = c("Up" = "#E41A1C", "Down" = "#377EB8"),
                        name = "Direction") +
    scale_size_continuous(range = c(2, 8), name = "NES") +
    geom_vline(xintercept = -log10(0.05), linetype = "dashed", colour = "grey50") +
    labs(x = "-log10(adj. p-value)", y = NULL,
         title = glue("GSEA — Hallmark gene sets — {obj$celltype_name}")) +
    theme_bw() +
    theme(axis.text.y = element_text(size = 8))
}

# gene_set: one of "full", "min", "leading"
# split: whether to split columns by Group
plot_tnfa_heatmap <- function(obj, gene_set = c("full", "min", "leading"), split = TRUE) {
  
  gene_set <- match.arg(gene_set)
  
  tnfa_subset <- switch(gene_set,
    "full"    = obj$tnfa_genes,
    "min"     = obj$tnfa_genes[rownames(obj$tnfa_genes) %in% obj$tnfa_genes_min, ],
    "leading" = {
      if (is.null(obj$tnfa_genes_leading)) {
        message(glue("TNFa pathway not significant in {obj$celltype_name}"))
        return(invisible(NULL))
      }
      obj$tnfa_genes[rownames(obj$tnfa_genes) %in% obj$tnfa_genes_leading, ]
    }
  )
  
  label <- switch(gene_set,
    "full"    = "full TNFa gene set",
    "min"     = "min TNFa gene set",
    "leading" = "leading edge TNFa genes"
  )
  
  row_anno <- rowAnnotation(
    Significant = tnfa_subset$FDR < 0.05,
    logFC = anno_barplot(tnfa_subset$logFC, gp = gpar(fill = "grey40"),
                         border = FALSE, width = unit(2, "cm"))
  )
  
  ht <- Heatmap(
    obj$mat_z[rownames(tnfa_subset),
              colnames(obj$mat_z) %in% unique(obj$metadata_subset$sample.id)],
    name = "z-score",
    col  = colorRamp2(c(-2, 0, 2), c("blue", "white", "red")),
    cluster_rows    = FALSE,
    cluster_columns = TRUE,
    show_row_names  = TRUE,
    show_column_names = TRUE,
    top_annotation  = obj$sample_anno,
    right_annotation = row_anno,
    column_split    = if (split) obj$metadata_subset$Group else NULL,
    row_names_gp    = gpar(fontsize = 8),
    column_title    = NULL
  )
  
  draw(ht, column_title = glue("{obj$celltype_name} — {label}"))
}
```


```{r}
am   <- prepare_tnfa(idx = 1, celltype_name = "macro-alveolar", deg_results)
mono <- prepare_tnfa(idx = 6, celltype_name = "macro-monocyte-derived", deg_results)
```

```{r}
plot_barcode(am)
plot_barcode(mono)
```

```{r}
plot_gsea(am)
plot_gsea(mono)
```

```{r, fig.asp=1.75, fig.width=10}
plot_tnfa_heatmap(am, gene_set = "full", split = TRUE)
plot_tnfa_heatmap(mono, gene_set = "full", split = TRUE)
```

```{r}
plot_tnfa_heatmap(am,   gene_set = "min")
plot_tnfa_heatmap(mono, gene_set = "min")
```

```{r, fig.asp=1.25, fig.width=10}
plot_tnfa_heatmap(am,   gene_set = "leading")
plot_tnfa_heatmap(mono, gene_set = "leading")
```

# Session info










