---
title: "Figure 4"
author: "Jovana Maksimovic"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
site: workflowr::wflow_site
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load libraries.

```{r}
suppressPackageStartupMessages({
 library(SingleCellExperiment)
 library(edgeR)
 library(tidyverse)
 library(ggplot2)
 library(Seurat)
 library(glmGamPoi)
 library(dittoSeq)
 library(here)
 library(clustree)
 library(patchwork)
 library(AnnotationDbi)
 library(org.Hs.eg.db)
 library(glue)
 library(speckle)
 library(tidyHeatmap)
 library(paletteer)
 library(dsb)
 library(ggh4x)
  library(readxl)
})

source(here("code/utility.R"))
```

# Load data

```{r}
files <- list.files(here("data/C133_Neeland_merged"),
                    pattern = "C133_Neeland_full_clean.*(macrophages|t_cells|other_cells)_annotated_diet.SEU.rds",
                    full.names = TRUE)

seuLst <- lapply(files[2:4], function(f) readRDS(f))

seu <- merge(seuLst[[1]], 
             y = c(seuLst[[2]], 
                   seuLst[[3]]))
seu
```


```{r, echo=FALSE}
# cleanup obsolete objects
rm(seuLst)
gc()
```


Create sample meta data table.

```{r}
props <- getTransformedProps(clusters = seu$ann_level_3,
                             sample = seu$sample.id, transform="asin")

seu@meta.data %>%
  dplyr::select(sample.id,
                Participant,
                Disease,
                Treatment,
                Severity,
                Group,
                Group_severity,
                Batch, 
                Age, 
                Sex) %>%
     left_join(props$Counts %>% 
                 data.frame %>%
                 group_by(sample) %>%
                 summarise(ncells = sum(Freq)),
               by = c("sample.id" = "sample")) %>%
    distinct() -> info

head(info) %>% knitr::kable()
```

# Prepare figure panels

Set up short/better names for cell types and conditions in figure.

```{r}
lab_map <- c(
  "macro-alveolar"          = "AM",
  "macro-IGF1"              = "AM.IGF1",
  "macro-CCL"               = "AM.CCL",
  "macro-lipid"             = "AM.Lipid",
  "macro-MT"                = "AM.MT",
  "macro-IFN"               = "AM.IFN",
  "macro-APOC2+"            = "AM.APOC2",
  "macro-CCL18"             = "AM.CCL18",
  "macro-IFI27"             = "AM.IFI27",
  "macro-monocyte-derived"  = "Mac.Mono.Deriv",
  "macro-interstitial"      = "Mac.Interstitial",
  "macro-lipid-APOC2+"      = "AM.Lipid.APOC2",
  "macro-T"                 = "Mac.T",
  "macro-IFI27+CCL18+"      = "AM.IFI27.CCL18",
  "macro-IFI27+APOC2+"      = "AM.IFI27.APOC2",
  "macro-proliferating"     = "Mac.Prolif",
  "macrophages"             = "All Mac (exc. Prolif)"
)

samp_map <-
c(
  "CF.NO_MOD.S" = "CF (no mod)(S)", 
  "CF.NO_MOD.M" = "CF (no mod)(M)"
)
```

```{r, fig.asp=0.5}
# HSP+ B, CD4 T-IFN

props <- getTransformedProps(clusters = seu$ann_level_3[!str_detect(seu$ann_level_3, "macro")],
                             sample = seu$sample.id[!str_detect(seu$ann_level_3, "macro")], transform="asin")

props$Proportions %>% data.frame %>%
  left_join(info,
            by = c("sample" = "sample.id")) %>%
  dplyr::filter(Group_severity %in% c("CF.NO_MOD.S", "CF.NO_MOD.M"),
                clusters %in% c("CD4 T-IFN", 
                                "HSP+ B cells")) -> dat

sig_names <- as_labeller(
     c("CD4 T-IFN" = "CD4 T-IFN",
       "HSP+ B cells" = "HSP+ B cells"))

pal <- setNames(RColorBrewer::brewer.pal(2, "Accent"),
                unname(samp_map))
  
dat %>%
  mutate(Group_severity = samp_map[Group_severity]) %>%
ggplot(aes(x = Group_severity,
                y = Freq,
                colour = Group_severity)) +
  geom_jitter(stat = "identity",
              width = 0.15,
              size = 2) +
  theme_classic() +
  theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(7),
          legend.position = "bottom",
          legend.direction = "horizontal",
          strip.text = element_text(size = 8)) +
  labs(x = "Group", y = "Proportion",
       colour = "Group") +
  facet_wrap(~clusters, scales = "free_y", ncol = 4,
             labeller = sig_names) +
  stat_summary(
    geom = "point",
    fun.y = "mean",
    col = "black",
    shape = "_",
    size = 10) +
  scale_color_manual(values = pal) -> p1

p1
```

```{r}
seu@meta.data %>% 
    data.frame %>% 
    dplyr::select(ann_level_2) %>%
    dplyr::filter(str_detect(ann_level_2, "macro")) %>%
    group_by(ann_level_2) %>% 
    count() %>%
    janitor::adorn_totals(name = "macrophages") %>%
    arrange(-n) %>%
    dplyr::rename(cell = ann_level_2) -> cell_freq

cell_freq
```

```{r}
files <- list.files(here("data/intermediate_objects"),
            pattern = "macro.*CF_samples", 
            full.names = TRUE) 
 
cutoff <- 0.05 
cont_name <- "CF.NO_MOD.SvCF.NO_MOD.M"  
lfc_cutoff <- 0
suffix <- ".CF_samples.fit.rds"
  
get_deg_data(files, cont_name, cell_freq, treat_lfc = lfc_cutoff,
             suffix = suffix) -> dat
```


```{r}
genes <- c("ARHGEF5",
           "GPD1",
           "ITGA1",
           "SIRPB1",
           "TLCD4",
           "GBP3",
           "CLIC2",
           "LILRB2",
           "MMP14",
           "SLC28A3",
           "SLC46A1",
           "ARPIN",
           "CTSK",
           "VAMP5")

dat %>%
  dplyr::select(gene, cell, logFC) %>%
  distinct() %>%
  dplyr::filter(gene %in% sort(genes)) %>%
  pivot_wider(
    names_from = cell,        # Column whose values become new column names
    values_from = logFC,
    values_fill = list(logFC = NA)) %>%
   arrange(across(all_of(cell_freq$cell[cell_freq$cell %in% .$cell]))) %>%
  column_to_rownames(var = "gene") -> dat_lfc
```

```{r, fig.asp=0.5}
col_fun <- circlize::colorRamp2(seq(0, 100000, length.out = 9), 
                                (RColorBrewer::brewer.pal(9, "PiYG")))
col_split <- c(rep("aggregate", 1), rep("sub-type", ncol(dat_lfc) - 1))

pal_dt <- c(paletteer::paletteer_d("RColorBrewer::Set1")[2:1], "grey") 
col_lfc_fun <- circlize::colorRamp2(seq(-2, 2, length.out = 3), 
                                    c(pal_dt[1], "white", pal_dt[2]))

ComplexHeatmap::HeatmapAnnotation(df = cell_freq %>%
                                    dplyr::filter(cell %in% colnames(dat_lfc)) %>%
                                    column_to_rownames(var = "cell") %>%
                                    dplyr::rename(`No. cells` = n),
                                  which = "column",
                                  show_annotation_name = FALSE,
                                  col = list(`No. cells` = col_fun),
                                  annotation_legend_param = list(
                                    `No. cells` = list(direction = "vertical",
                                                       labels_gp = grid::gpar(fontsize = 7)))) -> col_ann

colnames(dat_lfc) <- lab_map[colnames(dat_lfc)]
ComplexHeatmap::Heatmap(dat_lfc,
                        name = "logFC",
                        column_split = col_split,
                        column_title = NULL,
                        cluster_rows = FALSE,
                        cluster_columns = FALSE,
                        rect_gp = grid::gpar(col = "white", lwd = 1),
                        row_names_gp = grid::gpar(fontsize = 8),
                        column_names_gp = grid::gpar(fontsize = 8,
                                                     just = "centre"),
                        column_names_rot = 0,
                        column_names_centered = TRUE,
                        top_annotation = col_ann,
                        col = col_lfc_fun,
                        heatmap_legend_param = list(direction = "vertical",
                                                    labels_gp = grid::gpar(fontsize = 7))) -> plot_lfc

ComplexHeatmap::draw(as(list(plot_lfc), "HeatmapList"), 
                     heatmap_legend_side = "right", 
                     annotation_legend_side = "right",
                     merge_legends = TRUE) -> plot_lfc
plot_lfc
```

```{r}
bind_rows(lapply(files, function(f){
  deg_results <- readRDS(f)
  lrt <- glmLRT(deg_results$fit, 
                contrast = deg_results$contr[,cont_name])
  tmp <- cbind(summary(decideTests(lrt, p.value = cutoff)) %>% data.frame,
                    cell = str_extract(basename(f), "^[^.]+"))
  tmp
})) -> dat_deg
```

```{r}
dat_deg %>% 
  left_join(cell_freq) -> dat_deg

dat_deg %>%
  dplyr::filter(Var1 != "NotSig") %>%
  mutate(cell = lab_map[as.character(cell)]) %>%
  ggplot(aes(x = fct_reorder(cell, -n), y = Freq, fill = Var1)) +
  geom_col(position = "dodge") +
  scale_fill_manual(values = pal_dt) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 0,
                                   hjust = 0.5,
                                   vjust = 1,
                                   size = 8),
        legend.position = "top") +
  geom_text(aes(label = Freq), 
            position = position_dodge(width = 0.9),
            vjust = -0.5,
            size = 2.5) +
  labs(x = "Cell Type",
       y = "No. DEG (FDR < 0.05)",
       fill = "Direction") -> deg_barplot

deg_barplot
```

```{r}
get_deg_data(files, cont_name, cell_freq, treat_lfc = lfc_cutoff,
             suffix = suffix, cutoff = 1) -> dat_all

dat_all %>% 
  left_join(cell_freq) %>%
  mutate(Direction = as.factor(ifelse(sig == -1, "Down",
                                      ifelse(sig == 1, "Up", "N.S."))),
         cell = fct_reorder(cell, -n)) -> dat_all
```

```{r, fig.asp=1.5}
library(purrr)

# Function to extract normalized counts from one file
extract_norm_counts <- function(file) {
  # Get cell type from file name
  cell_type <- gsub("^.*/|\\.CF_samples\\.fit\\.rds$", "", file)
  
  # Load the RDS object
  dat <- readRDS(file)
  
  # Extract normalized counts
  counts <- as.data.frame(dat$adj$normalizedCounts)
  counts$gene <- rownames(counts)
  
  # Convert to long format: gene × sample × count
  counts_long <- counts %>%
    pivot_longer(-gene, names_to = "sample", values_to = "count") %>%
    mutate(celltype = cell_type)
  
  return(counts_long)
}

dat_norm_long <- map_dfr(files, extract_norm_counts) %>%
  dplyr::filter(gene %in% genes) %>%
  left_join(seu@meta.data %>%
              remove_rownames %>%
              dplyr::select(sample.id,
                            Group,
                            Group_severity,
                             Age) %>%
              distinct(),
            by = c("sample" = "sample.id")) %>%
  dplyr::filter(Group == "CF.NO_MOD") %>%
  mutate(expr = log2(count + 0.5))

dat_norm_long %>%
  inner_join(dat_all, 
            by = c("gene" = "gene",
                   "celltype" = "cell")) -> dat_combined
```



```{r}
library(dplyr)
library(tidyr)
library(ComplexHeatmap)
library(circlize)
library(tibble)
library(grid)

plot_macro_heatmap <- function(dat_combined, sig_only = FALSE) {

  # --- 1. Subset main macrophage population ---
  dat_macro <- dat_combined %>%
    filter(celltype == "macrophages")
  
  # --- 2. Pivot to gene × sample matrix ---
  expr_mat <- dat_macro %>%
    dplyr::select(gene, sample, expr) %>%
    pivot_wider(names_from = sample, values_from = expr) %>%
    column_to_rownames("gene") %>%
    as.matrix()
  
  # --- 3. Optionally filter to genes significant in macrophages AND other subsets ---
  if (sig_only) {
    
    # Genes significant in macrophages
    sig_in_macro <- dat_combined %>%
      filter(celltype == "macrophages", sig != 0) %>%
      pull(gene) %>%
      unique()
    
    # Genes significant in at least one other subset
    sig_in_other <- dat_combined %>%
      filter(celltype != "macrophages", sig != 0) %>%
      pull(gene) %>%
      unique()
    
    genes_keep <- intersect(sig_in_macro, sig_in_other)
    genes_keep <- genes_keep[genes_keep %in% rownames(expr_mat)]
    
    if (length(genes_keep) == 0) {
      stop("No genes are significant in both macrophages and other subsets.")
    }
    
    expr_mat <- expr_mat[genes_keep, ]
    message(glue::glue("{length(genes_keep)} genes significant in macrophages and at least one other subset."))
  }
  
  # --- 4. Column annotation ---
  sample_anno <- dat_macro %>%
    dplyr::select(sample, Group_severity, Age) %>%
    distinct() %>%
    column_to_rownames("sample")
  
  ha_col <- HeatmapAnnotation(
    Severity = samp_map[sample_anno$Group_severity],
    Age      = sample_anno$Age,
    col = list(
      Severity = c(
        "CF (no mod)(S)" = "#A6DBA0",
        "CF (no mod)(M)" = "#C2A5CF"
      ),
      Age = colorRamp2(
        seq(min(dat_combined$Age), max(dat_combined$Age), length.out = 9),
        RColorBrewer::brewer.pal(9, "Purples")
      )
    ),
    annotation_name_side = "left",
    show_annotation_name = FALSE
  )
  
  # --- 5. Row annotation: significance in other subsets ---
  sig_other <- dat_combined %>%
    group_by(gene, celltype) %>%
    summarise(
      sig_dir = case_when(
        any(sig == 1)  ~ "Up",
        any(sig == -1) ~ "Down",
        TRUE           ~ "Not significant"
      ),
      .groups = "drop"
    ) %>%
    pivot_wider(names_from = celltype, values_from = sig_dir,
                values_fill = "Not significant") %>%
    filter(gene %in% rownames(expr_mat)) %>%
    column_to_rownames("gene")
  
  celltype_order <- dat_combined %>%
    distinct(celltype, n) %>%
    arrange(desc(n)) %>%
    pull(celltype)
  
  sig_other     <- sig_other[, celltype_order, drop = FALSE]
  sig_other_chr <- sig_other %>% mutate(across(everything(), as.character))
  # Remove macrophages column when plotting sig_only to avoid redundancy
  if (sig_only) {
    sig_other_chr <- sig_other_chr %>% dplyr::select(-any_of("macrophages"))
  }
  
  colnames(sig_other_chr) <- lab_map[colnames(sig_other_chr)]
  
  sig_colors <- c(
    "Up"              = "#E7298A",
    "Down"            = "#66C2A5",
    "Not significant" = "#E8E8E8"
  )
  
  ha_row <- rowAnnotation(
    df  = sig_other_chr,
    col = setNames(
      replicate(ncol(sig_other_chr), sig_colors, simplify = FALSE),
      colnames(sig_other_chr)
    ),
    show_legend          = FALSE,
    annotation_name_gp   = gpar(fontsize = 8),
    annotation_name_side = "top"
  )
  
  # --- 6. Z-score normalise ---
  expr_mat_z <- t(scale(t(expr_mat)))
  
  # --- 7. Build heatmap ---
  ht <- Heatmap(
    expr_mat_z,
    name             = "Expression",
    top_annotation   = ha_col,
    right_annotation = ha_row,
    show_row_names   = TRUE,
    show_column_names = TRUE,
    cluster_rows     = TRUE,
    cluster_columns  = TRUE,
    row_names_gp     = gpar(fontsize = 8),
    column_names_gp  = gpar(fontsize = 8),
    heatmap_legend_param = list(
      title = bquote(bold("Scaled log"[2]~"expression"))
    ),
    column_split = sample_anno$Group_severity,
    column_title = NULL
  )
  
  sig_legend <- Legend(
    title     = "Significant",
    at        = c("Up", "Down", "Not significant"),
    labels    = c("Up", "Down", "Not significant"),
    legend_gp = gpar(fill = sig_colors)
  )
  
  # Replace the draw block at the end of plot_macro_heatmap() with:
  list(ht = ht, sig_legend = sig_legend)
  # ComplexHeatmap::draw(as(list(ht), "HeatmapList"), 
  #                    heatmap_legend_side = "right", 
  #                    annotation_legend_side = "right",
  #                    merge_legends = TRUE) 
}
```

```{r}
# All genes
plot_macro_heatmap(dat_combined, sig_only = FALSE) -> ht_out

ht_out
```



# Figure 4


```{r, fig.width=12, fig.height=12}
ht_to_ggplot <- function(ht, legend_list = NULL, width = 10, height = 5, res = 300) {
  tmp <- tempfile(fileext = ".png")
  png(tmp, width = width, height = height, units = "in", res = res)
  draw(
    ht,
    annotation_legend_list = legend_list,
    heatmap_legend_side    = "right",
    annotation_legend_side = "right",
    merge_legend           = TRUE
  )
  dev.off()
  
  img <- png::readPNG(tmp)
  
  ggplot() +
    annotation_raster(img, xmin = 0, xmax = 1, ymin = 0, ymax = 1,
                    interpolate = FALSE) +
    theme_void()
}

# Use it
ht_panel <- ht_to_ggplot(
  ht          = ht_out$ht,
  legend_list = list(ht_out$sig_legend),
  width       = 10,
  height      = 6.67,
  res = 900
)

# Then in patchwork
layout <- "
ABB
CCC
CCC
"

wrap_elements(p1 + theme(legend.direction = "vertical",
                         plot.margin = margin(rep(0,4)))) +
wrap_elements(deg_barplot + theme(axis.title.x = element_blank(),
                                  legend.text = element_text(size = 8),
                                  plot.margin = margin(rep(0,4)))) +
ht_panel +
plot_layout(design = layout) +
plot_annotation(tag_levels = "A") &
theme(plot.tag = element_text(size = 24, face = "bold", family = "arial"))
```

# Supplement

```{r}
dat %>%
  dplyr::select(gene, cell, logFC) %>%
  distinct() %>%
  pivot_wider(
    names_from = cell,        # Column whose values become new column names
    values_from = logFC,
    values_fill = list(logFC = NA)) %>%
   arrange(across(all_of(cell_freq$cell[cell_freq$cell %in% .$cell]))) %>%
  column_to_rownames(var = "gene") -> dat_lfc_supp
```

```{r, fig.asp=1.5}
col_fun <- circlize::colorRamp2(seq(0, 100000, length.out = 9), 
                                (RColorBrewer::brewer.pal(9, "PiYG")))
col_split <- c(rep("aggregate", 1), rep("sub-type", ncol(dat_lfc_supp) - 1))

col_lfc_fun <- circlize::colorRamp2(seq(-2, 2, length.out = 3), 
                                    c(pal_dt[1], "white", pal_dt[2]))

ComplexHeatmap::HeatmapAnnotation(df = cell_freq %>%
                                    dplyr::filter(cell %in% colnames(dat_lfc_supp)) %>%
                                    column_to_rownames(var = "cell") %>%
                                    dplyr::rename(`No. cells` = n),
                                  which = "column",
                                  show_annotation_name = FALSE,
                                  col = list(`No. cells` = col_fun),
                                  annotation_legend_param = list(
                                    `No. cells` = list(direction = "vertical",
                                                       labels_gp = grid::gpar(fontsize = 7)))) -> col_ann

ComplexHeatmap::HeatmapAnnotation(df = data.frame(`Sig. ≥2 cell types` = (rowSums(!is.na(dat_lfc_supp)) > 1),
                                                  check.names = FALSE),
                                  which = "row",
                                  col = list(`Sig. ≥2 cell types` = c("FALSE" = "#fdcce5","TRUE" = "#8bd3c7")),
                                  annotation_legend_param = list(
                                    `Sig. ≥2 cell types` = list(direction = "vertical",
                                                    ncol = 1)),
                                  show_annotation_name = FALSE) -> row_ann

colnames(dat_lfc_supp) <- lab_map[colnames(dat_lfc_supp)]
ComplexHeatmap::Heatmap(dat_lfc_supp, 
                        name = "logFC",
                        column_split = col_split,
                        column_title = NULL,
                        cluster_rows = FALSE,
                        cluster_columns = FALSE,
                        rect_gp = grid::gpar(col = "white", lwd = 1),
                        row_names_gp = grid::gpar(fontsize = 7),
                        column_names_gp = grid::gpar(fontsize = 8),
                        column_names_rot = 90,
                        top_annotation = col_ann,
                        col = col_lfc_fun,
                        right_annotation = row_ann,
                        heatmap_legend_param = list(direction = "vertical",
                                                    labels_gp = grid::gpar(fontsize = 7))) -> plot_lfc

ComplexHeatmap::draw(as(list(plot_lfc), "HeatmapList"), 
                     heatmap_legend_side = "right", 
                     annotation_legend_side = "right",
                     merge_legends = TRUE) -> plot_lfc_supp
plot_lfc_supp
```


# Session info










