---
title: "Supplementary Figure 2"
subtitle: "ADT ann_level_3 expression"
author: "Jovana Maksimovic"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
site: workflowr::wflow_site
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load libraries.

```{r}
suppressPackageStartupMessages({
 library(SingleCellExperiment)
 library(edgeR)
 library(tidyverse)
 library(ggplot2)
 library(Seurat)
 library(glmGamPoi)
 library(dittoSeq)
 library(here)
 library(clustree)
 library(patchwork)
 library(AnnotationDbi)
 library(org.Hs.eg.db)
 library(glue)
 library(speckle)
 library(tidyHeatmap)
 library(paletteer)
 library(dsb)
 library(ggh4x)
 library(readxl)
})
```

# Load data

Load the ADT data from save, pre-processed objects.

```{r}
files <- list.files(here("data/C133_Neeland_merged"),
                    pattern = "C133_Neeland_full_clean.*(macrophages|t_cells|other_cells)_annotated_full.SEU.rds",
                    full.names = TRUE)

# read in the ADT data, excluding everything else
seuLst <- lapply(files, function(f){
  s <- readRDS(f)
  DefaultAssay(s) <- "ADT"
  DietSeurat(s, assays = "ADT", dimreducs = NULL)
})

adt_names <- rownames(seuLst[[1]][["ADT"]]@counts)
seuLst <- lapply(seuLst, function(s){
  DefaultAssay(s) <- "ADT"
  
  if(!all(rownames(s) == adt_names)){
    adt_counts <- s[["ADT"]]@counts
    rownames(adt_counts) <- adt_names
    CreateSeuratObject(counts = adt_counts,
                       assay = "ADT",
                       meta.data = s@meta.data)
    
  } else {
    s
  }
})

seuADT <- merge(seuLst[[1]], 
                y = c(seuLst[[2]], 
                      seuLst[[3]]))
seuADT <- seuADT[, seuADT$Batch != 0]
seuADT
```

# Prepare figure panels

Make data frame of proteins, clusters, expression levels.

```{r}
out <- here("data",
            "C133_Neeland_merged",
            glue("C133_Neeland_full_clean_all_cells_dsb.ADT.rds"))

read_csv(file = here("data",
                     "C133_Neeland_batch1",
                     "data",
                     "sample_sheets",
                     "ADT_features.csv")) -> adt_data
pattern <- "anti-human/mouse |anti-human/mouse/rat |anti-mouse/human "
adt_data$name <- gsub(pattern, "", adt_data$name)

if(!file.exists(out)){
  adt_data %>%
    dplyr::filter(grepl("[Ii]sotype", name)) %>%
    pull(name) -> isotype_controls
  
  # normalise ADT using DSB normalisation
  adt_dsb <- ModelNegativeADTnorm(cell_protein_matrix = seuADT[["ADT"]]@counts,
                                  denoise.counts = TRUE,
                                  use.isotype.control = TRUE,
                                  isotype.control.name.vec = isotype_controls)
  saveRDS(adt_dsb, file = out)
  
} else {
  adt_dsb <- readRDS(out)
  
}

seuADT[["ADT"]]@data <- adt_dsb
seuADT
```
```{r}
lab_map <- c(
  "macro-alveolar"          = "AM",
  "macro-IGF1"              = "AM.IGF1",
  "macro-CCL"               = "AM.CCL",
  "macro-lipid"             = "AM.Lipid",
  "macro-MT"                = "AM.MT",
  "macro-IFN"               = "AM.IFN",
  "macro-APOC2+"            = "AM.APOC2",
  "macro-CCL18"             = "AM.CCL18",
  "macro-IFI27"             = "AM.IFI27",
  "macro-monocyte-derived"  = "Mac.Mono.Deriv",
  "macro-interstitial"      = "Mac.Interstitial",
  "macro-lipid-APOC2+"      = "AM.Lipid.APOC2",
  "macro-T"                 = "Mac.T",
  "macro-IFI27+CCL18+"      = "AM.IFI27.CCL18",
  "macro-IFI27+APOC2+"      = "AM.IFI27.APOC2",
  "macro-proliferating"     = "Mac.Prolif",
  "macrophages"             = "All Macs (exc. Prolif)"
)
```

```{r}
seuADT$ann_level_3 <- ifelse(str_detect(seuADT$ann_level_3, "proliferating"),
                              "macro-proliferating",
                              seuADT$ann_level_3)
  
# map long labels to short labels
seuADT$short_labels <- lab_map[seuADT$ann_level_3]
# match ordering of the levels betwen long and short labels
lut <- unique(seuADT@meta.data[, c("ann_level_3", "short_labels")])
lut <- lut[match(levels(factor(seuADT$ann_level_3)), lut$ann_level_3), , drop = FALSE]
# update level ordering for short labels
seuADT$short_labels <- factor(seuADT$short_labels, 
                                   levels = unique(lut$short_labels))
```

```{r}
# ADTs <- read_csv(file = here("data",
#                        "Proteins_macs_22.04.22.csv"))
# pattern <- "anti-human/mouse |anti-human/mouse/rat |anti-mouse/human |anti-human "
# ADTs$Description <- gsub(pattern, "", ADTs$Description)
ADTs <- read_excel(here("data",
                          "cluster_annotations",
                          "marker_proteins_macrophages_supp.xlsx"))
ADTs$Description <- sub("^.*?\\s", "", ADTs$Description)

seuADT@meta.data %>%
  dplyr::filter(str_detect(ann_level_3, "^macro")) %>%
  dplyr::select(short_labels) %>%
  rownames_to_column(var = "cell") %>%
  inner_join(as.data.frame(t(seuADT[["ADT"]]@data)) %>%
               rownames_to_column(var = "cell")) %>%
  pivot_longer(c(-cell, -short_labels),
               names_to = "ADT",
               values_to = "Expression") %>%
  dplyr::group_by(short_labels, ADT) %>%
  dplyr::summarize(Expression = mean(Expression)) %>%
  ungroup() %>%
  right_join(ADTs, by = c("ADT" = "Description")) -> dat

plot(density(dat$Expression))
```

```{r}
dat %>%
  dplyr::rename("Protein" = "ADT.y",
                "ADT Exp." = "Expression",
                "Cell Type" = "short_labels") %>%
  tidyHeatmap::heatmap(
    .column = Protein,
    .row = `Cell Type`,
    .value = `ADT Exp.`,
    scale = "none",
    rect_gp = grid::gpar(col = "white", lwd = 1),
    show_row_names = TRUE, 
    cluster_rows = TRUE,
    cluster_columns = TRUE,
    column_names_gp = grid::gpar(fontsize = 8),
    column_title_gp = grid::gpar(fontsize = 10),
    row_names_gp = grid::gpar(fontsize = 8),
    row_title_gp = grid::gpar(fontsize = 10),
    column_title_side = "top",
    palette_value = circlize::colorRamp2(seq(-0.5, 1.5, length.out = 11),
                                         rev(RColorBrewer::brewer.pal(11, "RdYlBu"))),
    heatmap_legend_param = list(direction = "vertical")) %>%
  add_tile(`Cell Type`, show_legend = FALSE,
           show_annotation_name = FALSE,
           palette = paletteer_d("ggsci::category20_d3", 
                                 length(unique(dat$short_labels)))) %>%
    as_ComplexHeatmap() -> sfig_1a

sfig_1a
```

```{r}
lab_map <- c(
  "CD4 T cells"         = "CD4 T",
  "CD4 T-IFN"           = "CD4 T-IFN",
  "CD4 T-naïve"         = "CD4 T-naïve",   # use "CD4 naive" if you want ASCII
  "CD4 T-NFKB"          = "CD4 T-NFκB",    # use "CD4 NFKB" for ASCII
  "CD4 T-reg"           = "CD4 T-reg",
  "CD4 T-rm"            = "CD4 T-rm",
  "CD8 T-GZMK"          = "CD8 T-GZMK",
  "CD8 T-inflammasome"  = "CD8 T-inflam",
  "CD8 T-rm"            = "CD8 T-rm",
  "gamma delta T cells" = "γδ T",        # or "gd T"
  "innate lymphocytes"  = "ILC",
  "NK cells"            = "NK",
  "NK-T cells"          = "NKT",
  "proliferating T/NK"  = "Prolif T/NK"
)
```

Map long cell type labels to short labels.

```{r}
# map long labels to short labels
seuADT$short_labels <- lab_map[seuADT$ann_level_3]
# match ordering of the levels betwen long and short labels
lut <- unique(seuADT@meta.data[, c("ann_level_3", "short_labels")])
lut <- lut[match(levels(factor(seuADT$ann_level_3)), lut$ann_level_3), , drop = FALSE]
# update level ordering for short labels
seuADT$short_labels <- factor(seuADT$short_labels, 
                                   levels = unique(lut$short_labels))
```

```{r}
# ADTs <- read_csv(file = here("data",
#                        "Proteins_T-NK_22.04.22.csv"))
# pattern <- "anti-human/mouse |anti-human/mouse/rat |anti-mouse/human |anti-human "
# ADTs$Description <- gsub(pattern, "", ADTs$Description)

ADTs <- read_excel(here("data",
                          "cluster_annotations",
                          "marker_proteins_TNK_supp.xlsx"))
ADTs$Description <- sub("^.*?\\s", "", ADTs$Description)

seuADT@meta.data %>%
  dplyr::filter(!is.na(short_labels)) %>%
  dplyr::select(short_labels) %>%
  rownames_to_column(var = "cell") %>%
  inner_join(as.data.frame(t(seuADT[["ADT"]]@data)) %>%
               rownames_to_column(var = "cell")) %>%
  pivot_longer(c(-cell, -short_labels),
               names_to = "ADT",
               values_to = "Expression") %>%
  dplyr::group_by(short_labels, ADT) %>%
  dplyr::summarize(Expression = mean(Expression)) %>%
  ungroup() %>%
  right_join(ADTs, by = c("ADT" = "Description")) -> dat

plot(density(dat$Expression))
```



```{r}
dat %>%
  dplyr::rename("Protein" = "ADT.y",
                "ADT Exp." = "Expression",
                "Cell Type" = "short_labels") %>%
  tidyHeatmap::heatmap(
    .column = Protein,
    .row = `Cell Type`,
    .value = `ADT Exp.`,
    scale = "none",
    rect_gp = grid::gpar(col = "white", lwd = 1),
    show_row_names = TRUE, 
    cluster_rows = TRUE,
    cluster_columns = TRUE,
    column_names_gp = grid::gpar(fontsize = 8),
    column_title_gp = grid::gpar(fontsize = 10),
    row_names_gp = grid::gpar(fontsize = 8),
    row_title_gp = grid::gpar(fontsize = 10),
    column_title_side = "top",
    palette_value = circlize::colorRamp2(seq(-0.5, 2, length.out = 11),
                                         rev(RColorBrewer::brewer.pal(11, "RdYlBu"))),
    heatmap_legend_param = list(direction = "vertical")) %>%
  add_tile(`Cell Type`, show_legend = FALSE,
           show_annotation_name = FALSE,
           palette = paletteer_d("ggsci::category20b_d3",
                                 direction = -1)[1:length(unique(dat$short_labels))]) %>%
    as_ComplexHeatmap() -> sfig_1b

sfig_1b
```

```{r}
lab_map <- c(
  "B cells"                   = "B",
  "cDC1"                      = "cDC1",
  "cDC2"                      = "cDC2",
  "ciliated epithelial cells" = "Ciliated epi",
  "dividing innate cells"     = "Div innate",
  "HSP+ B cells"              = "HSP+ B",
  "mast cells"                = "Mast",
  "migratory DC"              = "Mig DC",
  "monocytes"                 = "Mono",
  "neutrophil-like"           = "Neut-like",
  "plasma B cells"            = "Plasma B",
  "plasmacytoid DC"           = "pDC",
  "secretory epithelial cells"= "Secretory epi"
)
```

Map long cell type labels to short labels.

```{r}
# map long labels to short labels
seuADT$short_labels <- lab_map[seuADT$ann_level_3]
# match ordering of the levels betwen long and short labels
lut <- unique(seuADT@meta.data[, c("ann_level_3", "short_labels")])
lut <- lut[match(levels(factor(seuADT$ann_level_3)), lut$ann_level_3), , drop = FALSE]
# update level ordering for short labels
seuADT$short_labels <- factor(seuADT$short_labels, 
                                   levels = unique(lut$short_labels))
```

```{r}
# ADTs <- read_csv(file = here("data",
#                        "Proteins_other_22.04.22.csv"))
# pattern <- "anti-human/mouse |anti-human/mouse/rat |anti-mouse/human |anti-human "
# ADTs$Description <- gsub(pattern, "", ADTs$Description)

ADTs <- read_excel(here("data",
                          "cluster_annotations",
                          "marker_proteins_other_supp.xlsx"))
ADTs$Description <- sub("^.*?\\s", "", ADTs$Description)

seuADT@meta.data %>%
  dplyr::filter(ann_level_1 %in% unique(seuLst[[1]]$ann_level_1)) %>%
  dplyr::select(short_labels) %>%
  rownames_to_column(var = "cell") %>%
  inner_join(as.data.frame(t(seuADT[["ADT"]]@data)) %>%
               rownames_to_column(var = "cell")) %>%
  pivot_longer(c(-cell, -short_labels),
               names_to = "ADT",
               values_to = "Expression") %>%
  dplyr::group_by(short_labels, ADT) %>%
  dplyr::summarize(Expression = mean(Expression)) %>%
  ungroup() %>%
  right_join(ADTs, by = c("ADT" = "Description")) -> dat

plot(density(dat$Expression))
```

```{r}
dat %>%
  dplyr::rename("Protein" = "ADT.y",
                "ADT Exp." = "Expression",
                "Cell Type" = "short_labels") %>%
  tidyHeatmap::heatmap(
    .column = Protein,
    .row = `Cell Type`,
    .value = `ADT Exp.`,
    scale = "none",
    rect_gp = grid::gpar(col = "white", lwd = 1),
    show_row_names = TRUE, 
    cluster_rows = TRUE,
    cluster_columns = TRUE,
    column_names_gp = grid::gpar(fontsize = 8),
    column_title_gp = grid::gpar(fontsize = 10),
    row_names_gp = grid::gpar(fontsize = 8),
    row_title_gp = grid::gpar(fontsize = 10),
    column_title_side = "top",
    palette_value = circlize::colorRamp2(seq(-1, 2, length.out = 11),
                                         rev(RColorBrewer::brewer.pal(11, "RdYlBu"))),
    heatmap_legend_param = list(direction = "vertical")) %>%
  add_tile(`Cell Type`, show_legend = FALSE,
           show_annotation_name = FALSE,
           palette = paletteer_d("ggsci::category20c_d3", 
                                 length(unique(dat$short_labels)))) %>%
    as_ComplexHeatmap() -> sfig_1c

sfig_1c
```

# Supplementary Figure 2

```{r, fig.asp=1.5, fig.width=8}
layout = "
A
B
C
"
(wrap_plots(list(sfig_1a %>% 
                   ComplexHeatmap::draw(heatmap_legend_side = "right",
                                        padding = unit(0, "mm")) %>% 
                   grid::grid.grabExpr())) +
    wrap_plots(list(sfig_1b %>% 
                      ComplexHeatmap::draw(heatmap_legend_side = "right",
                                           padding = unit(0, "mm")) %>% 
                      grid::grid.grabExpr())) +
    wrap_plots(list(sfig_1c %>% 
                      ComplexHeatmap::draw(heatmap_legend_side = "right",
                                           padding = unit(0, "mm")) %>% 
                      grid::grid.grabExpr()))) + 
  plot_layout(design = layout) +
  plot_annotation(tag_levels = list(c("A","B","C"))) &
  theme(plot.tag = element_text(size = 24,
                                face = "bold",
                                family = "arial"))
  
```


<!-- # Supplement -->

<!-- ```{r} -->
<!-- library(Seurat) -->
<!-- library(ComplexHeatmap) -->
<!-- library(circlize) -->
<!-- library(dplyr) -->
<!-- library(tibble) -->

<!-- # ── Preparation function ─────────────────────────────────────────────────────── -->

<!-- prepare_adt <- function(celltype_name) { -->

<!--   adt_hits <- c( -->
<!--     "CD44", -->
<!--     "CD69", -->
<!--     "CD83", -->
<!--     "CD54", -->
<!--     "CD275 (B7-H2; B7-RP1; ICOSL)" -->
<!--   ) -->

<!--   adt_labels <- c( -->
<!--     "CD44"                          = "CD44 (CD44)", -->
<!--     "CD69"                          = "CD69 (CD69)", -->
<!--     "CD83"                          = "CD83 (CD83)", -->
<!--     "CD54"                          = "CD54 (ICAM1)", -->
<!--     "CD275 (B7-H2; B7-RP1; ICOSL)" = "CD275 (ICOSLG)" -->
<!--   ) -->

<!--   # Filter metadata to cell type and groups of interest -->
<!--   meta <- seuADT@meta.data %>% -->
<!--     dplyr::filter(ann_level_2 == celltype_name, -->
<!--                   Group %in% c("CF.NO_MOD", "NON_CF.CTRL")) %>% -->
<!--     dplyr::select(sample.id, Group, Age) %>% -->
<!--     distinct() -->

<!--   # Get cells belonging to this cell type -->
<!--   cells <- rownames(seuADT@meta.data)[seuADT@meta.data$ann_level_2 == celltype_name & -->
<!--                                         seuADT@meta.data$Group %in% c("CF.NO_MOD", "NON_CF.CTRL")] -->

<!--   # Extract raw counts for cells of interest -->
<!--   adt_raw <- GetAssayData(seuADT, assay = "ADT", slot = "counts") -->
<!--   adt_sub <- adt_raw[adt_hits, cells] -->

<!--   # Pseudobulk: sum per sample then CPM normalise -->
<!--   expr_mat <- t(adt_sub) %>% -->
<!--     as.data.frame() %>% -->
<!--     mutate(sample.id = seuADT@meta.data[cells, "sample.id"]) %>% -->
<!--     group_by(sample.id) %>% -->
<!--     summarise(across(all_of(adt_hits), sum), .groups = "drop") %>% -->
<!--     dplyr::filter(sample.id %in% meta$sample.id) %>% -->
<!--     column_to_rownames("sample.id") %>% -->
<!--     as.matrix() %>% -->
<!--     t() -->

<!--   lib_sizes <- colSums(expr_mat) -->
<!--   expr_mat  <- sweep(expr_mat, 2, lib_sizes, "/") * 1e6 -->

<!--   # Z-score normalise -->
<!--   expr_mat_z <- t(scale(t(expr_mat))) -->

<!--   # Align metadata to matrix columns -->
<!--   sample_meta <- meta[match(colnames(expr_mat_z), meta$sample.id), ] -->

<!--   list( -->
<!--     celltype_name = celltype_name, -->
<!--     expr_mat_z    = expr_mat_z, -->
<!--     sample_meta   = sample_meta, -->
<!--     adt_labels    = adt_labels -->
<!--   ) -->
<!-- } -->

<!-- # ── Plot function ────────────────────────────────────────────────────────────── -->

<!-- plot_adt_heatmap <- function(obj) { -->

<!--   rdpu_colors <- colorRamp2( -->
<!--     seq(min(obj$sample_meta$Age, na.rm = TRUE), -->
<!--         max(obj$sample_meta$Age, na.rm = TRUE), -->
<!--         length.out = 9), -->
<!--     RColorBrewer::brewer.pal(9, "RdPu") -->
<!--   ) -->

<!--   ha_col <- HeatmapAnnotation( -->
<!--     Group = obj$sample_meta$Group, -->
<!--     Age   = obj$sample_meta$Age, -->
<!--     col   = list( -->
<!--       Group = c("CF.NO_MOD"   = "#C2A5CF", -->
<!--                 "NON_CF.CTRL" = "#A6DBA0"), -->
<!--       Age   = rdpu_colors -->
<!--     ), -->
<!--     show_annotation_name = TRUE, -->
<!--     annotation_name_side = "left" -->
<!--   ) -->

<!--   ht <- Heatmap( -->
<!--     obj$expr_mat_z, -->
<!--     name              = "Z-score", -->
<!--     col               = colorRamp2(c(-2, 0, 2), c("blue", "white", "red")), -->
<!--     top_annotation    = ha_col, -->
<!--     column_split      = obj$sample_meta$Group, -->
<!--     cluster_rows      = TRUE, -->
<!--     cluster_columns   = TRUE, -->
<!--     column_title      = NULL, -->
<!--     show_row_names    = TRUE, -->
<!--     show_column_names = TRUE, -->
<!--     row_labels        = obj$adt_labels[rownames(obj$expr_mat_z)], -->
<!--     row_names_gp      = gpar(fontsize = 9), -->
<!--     column_names_gp   = gpar(fontsize = 8), -->
<!--     heatmap_legend_param = list(title = "Z-score") -->
<!--   ) -->

<!--   draw(ht, -->
<!--        column_title           = obj$celltype_name, -->
<!--        heatmap_legend_side    = "right", -->
<!--        annotation_legend_side = "right", -->
<!--        merge_legend           = TRUE) -->
<!-- } -->
<!-- ``` -->

<!-- ```{r} -->
<!-- am   <- prepare_adt("macro-alveolar") -->
<!-- mono <- prepare_adt("macro-monocyte-derived") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot_adt_heatmap(am) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot_adt_heatmap(mono) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- prepare_rna_adt_cor <- function(celltype_name) { -->

<!--   adt_hits <- c( -->
<!--     "CD44", -->
<!--     "CD69", -->
<!--     "CD83", -->
<!--     "CD54", -->
<!--     "CD275 (B7-H2; B7-RP1; ICOSL)" -->
<!--   ) -->

<!--   gene_hits <- c("CD44", "CD69", "CD83", "ICAM1", "ICOSLG") -->

<!--   adt_to_gene <- c( -->
<!--     "CD44"                          = "CD44", -->
<!--     "CD69"                          = "CD69", -->
<!--     "CD83"                          = "CD83", -->
<!--     "CD54"                          = "ICAM1", -->
<!--     "CD275 (B7-H2; B7-RP1; ICOSL)" = "ICOSLG" -->
<!--   ) -->

<!--   # ── ADT pseudobulk ────────────────────────────────────────────────────────── -->
<!--   adt_cells <- rownames(seuADT@meta.data)[ -->
<!--     seuADT@meta.data$ann_level_2 == celltype_name & -->
<!--     seuADT@meta.data$Group %in% c("CF.NO_MOD", "NON_CF.CTRL") -->
<!--   ] -->

<!--   adt_meta <- seuADT@meta.data[adt_cells, ] %>% -->
<!--     dplyr::select(sample.id, Group, Age) %>% -->
<!--     distinct() -->

<!--   adt_raw <- GetAssayData(seuADT, assay = "ADT", slot = "counts") -->
<!--   adt_sub <- adt_raw[adt_hits, adt_cells] -->

<!--   rm(adt_raw) -->
<!--   gc() -->

<!--   adt_pb <- t(adt_sub) %>% -->
<!--     as.data.frame() %>% -->
<!--     mutate(sample.id = seuADT@meta.data[adt_cells, "sample.id"]) %>% -->
<!--     group_by(sample.id) %>% -->
<!--     summarise(across(all_of(adt_hits), sum), .groups = "drop") %>% -->
<!--     column_to_rownames("sample.id") %>% -->
<!--     as.matrix() %>% -->
<!--     t() -->

<!--   rm(adt_sub) -->
<!--   gc() -->

<!--   lib_sizes <- colSums(adt_pb) -->
<!--   adt_cpm   <- sweep(adt_pb, 2, lib_sizes, "/") * 1e6 -->

<!--   rm(adt_pb) -->
<!--   gc() -->

<!--   # Rename ADT rows to gene symbols for matching -->
<!--   rownames(adt_cpm) <- adt_to_gene[rownames(adt_cpm)] -->

<!--   # ── RNA pseudobulk ─────────────────────────────────────────────────────────── -->
<!--   seu_rna <- lapply(files, readRDS) %>% -->
<!--     Filter(function(s) celltype_name %in% s@meta.data$ann_level_2, .) %>% -->
<!--     .[[1]] -->

<!--   rna_cells <- rownames(seu_rna@meta.data)[ -->
<!--     seu_rna@meta.data$ann_level_2 == celltype_name & -->
<!--     seu_rna@meta.data$Group %in% c("CF.NO_MOD", "NON_CF.CTRL") -->
<!--   ] -->

<!--   # Extract only what we need before discarding the full object -->
<!--   rna_counts     <- GetAssayData(seu_rna, assay = "RNA", slot = "counts") -->
<!--   rna_sub        <- rna_counts[gene_hits[gene_hits %in% rownames(rna_counts)], rna_cells] -->
<!--   rna_sample_ids <- seu_rna@meta.data[rna_cells, "sample.id"] -->

<!--   rm(seu_rna, rna_counts) -->
<!--   gc() -->

<!--   rna_pb <- t(rna_sub) %>% -->
<!--     as.data.frame() %>% -->
<!--     mutate(sample.id = rna_sample_ids) %>% -->
<!--     group_by(sample.id) %>% -->
<!--     summarise(across(everything(), sum), .groups = "drop") %>% -->
<!--     column_to_rownames("sample.id") %>% -->
<!--     as.matrix() %>% -->
<!--     t() -->

<!--   rm(rna_sub) -->
<!--   gc() -->

<!--   lib_sizes_rna <- colSums(rna_pb) -->
<!--   rna_cpm       <- sweep(rna_pb, 2, lib_sizes_rna, "/") * 1e6 -->
<!--   rna_log       <- log2(rna_cpm + 1) -->
<!--   adt_log       <- log2(adt_cpm + 1) -->

<!--   rm(rna_pb, rna_cpm, adt_cpm) -->
<!--   gc() -->

<!--   # ── Align samples ──────────────────────────────────────────────────────────── -->
<!--   shared_samples <- intersect(colnames(rna_log), colnames(adt_log)) -->
<!--   rna_log        <- rna_log[, shared_samples] -->
<!--   adt_log        <- adt_log[, shared_samples] -->

<!--   # ── Compute per-gene Spearman correlation ──────────────────────────────────── -->
<!--   cor_res <- lapply(gene_hits, function(g) { -->
<!--     if (!g %in% rownames(rna_log) | !g %in% rownames(adt_log)) return(NULL) -->
<!--     test <- cor.test(rna_log[g, ], adt_log[g, ], method = "spearman") -->
<!--     data.frame( -->
<!--       gene = g, -->
<!--       rho  = test$estimate, -->
<!--       pval = test$p.value -->
<!--     ) -->
<!--   }) %>% -->
<!--     bind_rows() %>% -->
<!--     mutate(padj = p.adjust(pval, method = "BH")) -->

<!--   list( -->
<!--     celltype_name  = celltype_name, -->
<!--     rna_log        = rna_log, -->
<!--     adt_log        = adt_log, -->
<!--     cor_res        = cor_res, -->
<!--     shared_samples = shared_samples, -->
<!--     adt_to_gene    = adt_to_gene, -->
<!--     gene_hits      = gene_hits -->
<!--   ) -->
<!-- } -->

<!-- # ── Scatter plots: one per gene ──────────────────────────────────────────────── -->

<!-- plot_rna_adt_scatter <- function(obj) { -->

<!--   plots <- lapply(obj$gene_hits, function(g) { -->
<!--     if (!g %in% rownames(obj$rna_log) | !g %in% rownames(obj$adt_log)) return(NULL) -->

<!--     cor_label <- obj$cor_res %>% -->
<!--       filter(gene == g) %>% -->
<!--       mutate(label = glue("rho = {round(rho, 2)}, padj = {round(padj, 3)}")) %>% -->
<!--       pull(label) -->

<!--     df <- data.frame( -->
<!--       RNA = obj$rna_log[g, obj$shared_samples], -->
<!--       ADT = obj$adt_log[g, obj$shared_samples] -->
<!--     ) %>% -->
<!--       filter(RNA > 0) -->

<!--     df %>% -->
<!--       ggplot(aes(x = RNA, y = ADT)) + -->
<!--       geom_point(colour = "#E41A1C", size = 2) + -->
<!--       geom_smooth(method = "lm", se = TRUE, colour = "grey40", linewidth = 0.8) + -->
<!--       annotate("text", x = -Inf, y = Inf, hjust = -0.1, vjust = 1.5, -->
<!--                label = cor_label, size = 3) + -->
<!--       labs(x = glue("{g} RNA (log2 CPM)"), -->
<!--            y = glue("{g} ADT (log2 CPM)"), -->
<!--            title = glue("{g} (n = {nrow(df)} samples)")) + -->
<!--       theme_bw() -->
<!--   }) %>% -->
<!--     Filter(Negate(is.null), .) -->

<!--   wrap_plots(plots, ncol = 3) + -->
<!--     plot_annotation(title = glue("RNA vs ADT correlation — {obj$celltype_name}")) -->
<!-- } -->

<!-- # ── Correlation matrix heatmap ───────────────────────────────────────────────── -->

<!-- plot_rna_adt_cor_heatmap <- function(obj) { -->

<!--   rna_scaled <- t(scale(t(obj$rna_log[obj$gene_hits[obj$gene_hits %in% rownames(obj$rna_log)], ]))) -->
<!--   adt_scaled <- t(scale(t(obj$adt_log[obj$gene_hits[obj$gene_hits %in% rownames(obj$adt_log)], ]))) -->

<!--   cor_mat <- cor(t(rna_scaled), t(adt_scaled), method = "spearman") -->

<!--   col_fun <- colorRamp2(c(-1, 0, 1), c("#377EB8", "white", "#E41A1C")) -->

<!--   draw( -->
<!--     Heatmap( -->
<!--       cor_mat, -->
<!--       name              = "Spearman rho", -->
<!--       col               = col_fun, -->
<!--       cluster_rows      = TRUE, -->
<!--       cluster_columns   = TRUE, -->
<!--       show_row_names    = TRUE, -->
<!--       show_column_names = TRUE, -->
<!--       row_names_gp      = gpar(fontsize = 9), -->
<!--       column_names_gp   = gpar(fontsize = 9), -->
<!--       heatmap_legend_param = list(title = "Spearman rho") -->
<!--     ), -->
<!--     column_title = glue("RNA vs ADT correlation — {obj$celltype_name}") -->
<!--   ) -->
<!-- } -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # ── Prepare objects ──────────────────────────────────────────────────────────── -->

<!-- am_cor   <- prepare_rna_adt_cor("macro-alveolar") -->
<!-- mono_cor <- prepare_rna_adt_cor("macro-monocyte-derived") -->

<!-- # ── Scatter plots ────────────────────────────────────────────────────────────── -->

<!-- plot_rna_adt_scatter(am_cor) -->
<!-- plot_rna_adt_scatter(mono_cor) -->

<!-- # ── Correlation heatmaps ─────────────────────────────────────────────────────── -->

<!-- plot_rna_adt_cor_heatmap(am_cor) -->
<!-- plot_rna_adt_cor_heatmap(mono_cor) -->
<!-- ``` -->

# Session info










