---
title: "Integrate all cells"
author: "Jovana Maksimovic"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
site: workflowr::wflow_site
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load libraries.

```{r}
suppressPackageStartupMessages({
 library(SingleCellExperiment)
 library(edgeR)
 library(tidyverse)
 library(ggplot2)
 library(Seurat)
 library(glmGamPoi)
 library(dittoSeq)
 library(here)
 library(clustree)
 library(patchwork)
 library(AnnotationDbi)
 library(org.Hs.eg.db)
 library(glue)
 library(speckle)
 library(tidyHeatmap)
 library(paletteer)
 library(dsb)
 library(ggh4x)
 library(readxl)
})
```

# Load data

```{r}
files <- list.files(here("data/C133_Neeland_merged"),
                    pattern = "C133_Neeland_full_clean.*(macrophages|t_cells|other_cells)_annotated_full.SEU.rds",
                    full.names = TRUE)

seuLst <- lapply(files[2:4], function(f) readRDS(f))

adt_names <- rownames(seuLst[[1]][["ADT"]]@counts)
seuLst <- lapply(seuLst, function(s){
  DefaultAssay(s) <- "ADT"
  
  if(!all(rownames(s) == adt_names)){
    adt_counts <- s[["ADT"]]@counts
    rownames(adt_counts) <- adt_names
    CreateSeuratObject(counts = adt_counts,
                       assay = "ADT",
                       meta.data = s@meta.data)
    
  } else {
    DietSeurat(s, assays = "ADT", dimreducs = NULL)
    
  }
  
})

seuADT <- merge(seuLst[[1]], 
                y = c(seuLst[[2]], 
                      seuLst[[3]]))
seuADT <- seuADT[, seuADT$Batch != 0]
seuADT
```

Visualise ADTs
Make data frame of proteins, clusters, expression levels.

```{r}
out <- here("data",
            "C133_Neeland_merged",
            glue("C133_Neeland_full_clean_all_cells_dsb.ADT.rds"))

read_csv(file = here("data",
                     "C133_Neeland_batch1",
                     "data",
                     "sample_sheets",
                     "ADT_features.csv")) -> adt_data
pattern <- "anti-human/mouse |anti-human/mouse/rat |anti-mouse/human "
adt_data$name <- gsub(pattern, "", adt_data$name)

if(!file.exists(out)){
  adt_data %>%
    dplyr::filter(grepl("[Ii]sotype", name)) %>%
    pull(name) -> isotype_controls
  
  # normalise ADT using DSB normalisation
  adt_dsb <- ModelNegativeADTnorm(cell_protein_matrix = seuADT[["ADT"]]@counts,
                                  denoise.counts = TRUE,
                                  use.isotype.control = TRUE,
                                  isotype.control.name.vec = isotype_controls)
  saveRDS(adt_dsb, file = out)
  
} else {
  adt_dsb <- readRDS(out)
  
}

seuADT[["ADT"]]@data <- adt_dsb
seuADT
```

```{r}
# ADTs <- read_csv(file = here("data",
#                        "Proteins_macs_22.04.22.csv"))
# pattern <- "anti-human/mouse |anti-human/mouse/rat |anti-mouse/human |anti-human "
# ADTs$Description <- gsub(pattern, "", ADTs$Description)
ADTs <- read_excel(here("data",
                          "cluster_annotations",
                          "marker_proteins_macrophages_supp.xlsx"))
ADTs$Description <- sub("^.*?\\s", "", ADTs$Description)

seuADT@meta.data %>%
  dplyr::filter(str_detect(ann_level_3, "^macro")) %>%
  dplyr::select(ann_level_3) %>%
  rownames_to_column(var = "cell") %>%
  inner_join(as.data.frame(t(seuADT[["ADT"]]@data)) %>%
               rownames_to_column(var = "cell")) %>%
  pivot_longer(c(-cell, -ann_level_3),
               names_to = "ADT",
               values_to = "Expression") %>%
  dplyr::group_by(ann_level_3, ADT) %>%
  dplyr::summarize(Expression = mean(Expression)) %>%
  ungroup() %>%
  right_join(ADTs, by = c("ADT" = "Description")) -> dat

plot(density(dat$Expression))
```

```{r}
dat %>%
  dplyr::rename("Protein" = "ADT.y",
                "Mean Exp." = "Expression",
                "Cell Type" = "ann_level_3") %>%
  tidyHeatmap::heatmap(
    .column = Protein,
    .row = `Cell Type`,
    .value = `Mean Exp.`,
    scale = "none",
    rect_gp = grid::gpar(col = "white", lwd = 1),
    show_row_names = TRUE, 
    cluster_rows = FALSE,
    cluster_columns = TRUE,
    column_names_gp = grid::gpar(fontsize = 8),
    column_title_gp = grid::gpar(fontsize = 10),
    row_names_gp = grid::gpar(fontsize = 8),
    row_title_gp = grid::gpar(fontsize = 10),
    column_title_side = "top",
    palette_value = circlize::colorRamp2(seq(-0.5, 1.5, length.out = 11),
                                         #viridis::magma(11)),
                                         rev(RColorBrewer::brewer.pal(11, "Spectral"))),
    heatmap_legend_param = list(direction = "vertical")) %>%
  add_tile(`Cell Type`, show_legend = FALSE,
           show_annotation_name = FALSE,
           palette = paletteer_d("ggsci::category20_d3", 
                                 length(unique(dat$ann_level_3)))) %>%
    as_ComplexHeatmap() -> sfig_1a

sfig_1a
```

```{r}
# ADTs <- read_csv(file = here("data",
#                        "Proteins_T-NK_22.04.22.csv"))
# pattern <- "anti-human/mouse |anti-human/mouse/rat |anti-mouse/human |anti-human "
# ADTs$Description <- gsub(pattern, "", ADTs$Description)

ADTs <- read_excel(here("data",
                          "cluster_annotations",
                          "marker_proteins_TNK_supp.xlsx"))
ADTs$Description <- sub("^.*?\\s", "", ADTs$Description)

seuADT@meta.data %>%
  dplyr::filter(ann_level_1 %in% unique(seuLst[[2]]$ann_level_1)) %>%
  dplyr::select(ann_level_3) %>%
  rownames_to_column(var = "cell") %>%
  inner_join(as.data.frame(t(seuADT[["ADT"]]@data)) %>%
               rownames_to_column(var = "cell")) %>%
  pivot_longer(c(-cell, -ann_level_3),
               names_to = "ADT",
               values_to = "Expression") %>%
  dplyr::group_by(ann_level_3, ADT) %>%
  dplyr::summarize(Expression = mean(Expression)) %>%
  ungroup() %>%
  right_join(ADTs, by = c("ADT" = "Description")) -> dat

plot(density(dat$Expression))
```

```{r}
dat %>%
  dplyr::rename("Protein" = "ADT.y",
                "Mean Exp." = "Expression",
                "Cell Type" = "ann_level_3") %>%
  tidyHeatmap::heatmap(
    .column = Protein,
    .row = `Cell Type`,
    .value = `Mean Exp.`,
    scale = "none",
    rect_gp = grid::gpar(col = "white", lwd = 1),
    show_row_names = TRUE, 
    cluster_rows = FALSE,
    cluster_columns = TRUE,
    column_names_gp = grid::gpar(fontsize = 8),
    column_title_gp = grid::gpar(fontsize = 10),
    row_names_gp = grid::gpar(fontsize = 8),
    row_title_gp = grid::gpar(fontsize = 10),
    column_title_side = "top",
    palette_value = circlize::colorRamp2(seq(-0.5, 2, length.out = 11),
                                         #viridis::magma(11)),
                                         rev(RColorBrewer::brewer.pal(11, "Spectral"))),
    heatmap_legend_param = list(direction = "vertical")) %>%
  add_tile(`Cell Type`, show_legend = FALSE,
           show_annotation_name = FALSE,
           palette = paletteer_d("ggsci::category20b_d3",
                                 direction = -1)[1:length(unique(dat$ann_level_3))]) %>%
    as_ComplexHeatmap() -> sfig_1b

sfig_1b
```

```{r}
# ADTs <- read_csv(file = here("data",
#                        "Proteins_other_22.04.22.csv"))
# pattern <- "anti-human/mouse |anti-human/mouse/rat |anti-mouse/human |anti-human "
# ADTs$Description <- gsub(pattern, "", ADTs$Description)

ADTs <- read_excel(here("data",
                          "cluster_annotations",
                          "marker_proteins_other_supp.xlsx"))
ADTs$Description <- sub("^.*?\\s", "", ADTs$Description)

seuADT@meta.data %>%
  dplyr::filter(ann_level_1 %in% unique(seuLst[[1]]$ann_level_1)) %>%
  dplyr::select(ann_level_3) %>%
  rownames_to_column(var = "cell") %>%
  inner_join(as.data.frame(t(seuADT[["ADT"]]@data)) %>%
               rownames_to_column(var = "cell")) %>%
  pivot_longer(c(-cell, -ann_level_3),
               names_to = "ADT",
               values_to = "Expression") %>%
  dplyr::group_by(ann_level_3, ADT) %>%
  dplyr::summarize(Expression = mean(Expression)) %>%
  ungroup() %>%
  right_join(ADTs, by = c("ADT" = "Description")) -> dat

plot(density(dat$Expression))
```

```{r}
dat %>%
  dplyr::rename("Protein" = "ADT.y",
                "DSB Exp." = "Expression",
                "Cell Type" = "ann_level_3") %>%
  tidyHeatmap::heatmap(
    .column = Protein,
    .row = `Cell Type`,
    .value = `DSB Exp.`,
    scale = "none",
    rect_gp = grid::gpar(col = "white", lwd = 1),
    show_row_names = TRUE, 
    cluster_rows = FALSE,
    cluster_columns = TRUE,
    column_names_gp = grid::gpar(fontsize = 8),
    column_title_gp = grid::gpar(fontsize = 10),
    row_names_gp = grid::gpar(fontsize = 8),
    row_title_gp = grid::gpar(fontsize = 10),
    column_title_side = "top",
    palette_value = circlize::colorRamp2(seq(-1, 2, length.out = 11),
                                         #viridis::magma(11)),
                                         rev(RColorBrewer::brewer.pal(11, "Spectral"))),
    heatmap_legend_param = list(direction = "vertical")) %>%
  add_tile(`Cell Type`, show_legend = FALSE,
           show_annotation_name = FALSE,
           palette = paletteer_d("ggsci::category20c_d3", 
                                 length(unique(dat$ann_level_3)))) %>%
    as_ComplexHeatmap() -> sfig_1c

sfig_1c
```

```{r, fig.asp=1.75, fig.width=8}
layout = "
A
B
C
"
(wrap_plots(list(sfig_1a %>% 
                      ComplexHeatmap::draw(heatmap_legend_side = "right") %>% 
                      grid::grid.grabExpr())) +
    wrap_plots(list(sfig_1b %>% 
                      ComplexHeatmap::draw(heatmap_legend_side = "right") %>% 
                      grid::grid.grabExpr())) +
    wrap_plots(list(sfig_1c %>% 
                      ComplexHeatmap::draw(heatmap_legend_side = "right") %>% 
                      grid::grid.grabExpr()))) + 
  plot_layout(design = layout) +
  plot_annotation(tag_levels = list(c("A","B","C"))) &
  theme(plot.tag = element_text(size = 16,
                                face = "bold",
                                family = "arial"))
  
```

# Session info










